#!/bin/bash
./maximal -Rnxxa
./maximal -Rnxxb
./maximal -Rnxxc
./maximal -Rnxxd
./maximal -Rnxxe
./maximal -Rnxxf
./maximal -Rnxxg
./maximal -Rnxxh

./maximal -Rnxx Danan_ex3.txt
./maximal -Rnxx Dbipe_ex3.txt
./maximal -Rnxx Dbiar_ex3.txt
./maximal -Rnxx Derec_ex3.txt
./maximal -Rnxx Dmaur_ex3.txt
./maximal -Rnxx Dmela_ex3.txt
./maximal -Rnxx Dsant_ex3.txt
./maximal -Rnxx Dsech_ex3.txt
./maximal -Rnxx Dsimu_ex3.txt
./maximal -Rnxx Dsuzu_ex3.txt
./maximal -Rnxx Dyaku_ex3.txt

./maximal -Rnxx Dbiar_NEE.txt
./maximal -Rnxx Derec_NEE.txt
./maximal -Rnxx Dmaur_NEE.txt
./maximal -Rnxx Dmela_NEE.txt
./maximal -Rnxx Dsant_NEE.txt
./maximal -Rnxx Dsech_NEE.txt
./maximal -Rnxx Dsimu_NEE.txt
./maximal -Rnxx Dsuzu_NEE.txt
./maximal -Rnxx Dyaku_NEE.txt
./maximal -Rnxx Dmela_DWME.txt

./maximal -Rnxx solved-01-toslip_tricksy.txt
./maximal -Rnxx solved-02-toslip_tricksy.txt
./maximal -Rnxx solved-03-tosSt1_tricksy.txt
./maximal -Rnxx solved-04-tos-ct_tricksy.txt
./maximal -Rnxx solved-22-tosSt2_tricksy.txt
./maximal -Rnxx solved-23-tosSt2_tricksy.txt
./maximal -Rnxx solved-24-tosSt2_tricksy.txt
./maximal -Rnxx solved-25-tosSt2_tricksy.txt
./maximal -Rnxx solved-26-tosSt2_tricksy.txt
./maximal -Rnxx solved-29-toslp2_tricksy.txt
./maximal -Rnxx solved-30-toslp2_tricksy.txt
./maximal -Rnxx solved-44-tosimp_tricksy.txt
./maximal -Rnxx solved-31-t0edge_tricksy.txt
./maximal -Rnxx solved-05-koshp1_tricksy.txt
./maximal -Rnxx solved-06-koslip_tricksy.txt
./maximal -Rnxx solved-07-koslip_tricksy.txt
./maximal -Rnxx solved-08-koslp2_tricksy.txt
./maximal -Rnxx solved-09-koslp3_tricksy.txt
./maximal -Rnxx solved-18-koshp2_tricksy.txt
./maximal -Rnxx solved-19-koslp4_tricksy.txt
./maximal -Rnxx solved-45-cinky1_tricksy.txt
./maximal -Rnxx solved-46-cinky2_tricksy.txt
./maximal -Rnxx solved-10-cycle1_tricksy.txt
./maximal -Rnxx solved-11-cycle1_tricksy.txt
./maximal -Rnxx solved-12-cycle1_tricksy.txt
./maximal -Rnxx solved-13-cycle2_tricksy.txt
./maximal -Rnxx solved-14-cycle3_tricksy.txt
./maximal -Rnxx solved-15-cycle4_tricksy.txt
./maximal -Rnxx solved-17-cycle5_tricksy.txt
./maximal -Rnxx solved-16-cyc3_a_tricksy.txt
./maximal -Rnxx solved-20-cyc3_b_tricksy.txt
./maximal -Rnxx solved-21-cyc3_c_tricksy.txt
./maximal -Rnxx solved-27-cycleX_tricksy.txt
./maximal -Rnxx solved-32-combo1_tricksy.txt
./maximal -Rnxx solved-28-scrtch_tricksy.txt
./maximal -Rnxx solved-33-imprf1_tricksy.txt
./maximal -Rnxx solved-34-imprf2_tricksy.txt
./maximal -Rnxx solved-35-imprf3_tricksy.txt
./maximal -Rnxx solved-36-imprf4_tricksy.txt
./maximal -Rnxx solved-37-imprfk_tricksy.txt
./maximal -Rnxx solved-38-imprft_tricksy.txt
./maximal -Rnxx solved-39-imprfk_tricksy.txt
./maximal -Rnxx solved-40-imprfk_tricksy.txt
./maximal -Rnxx solved-43-timprf_tricksy.txt
./maximal -Rnxx solved-41-RNAnuc.txt
./maximal -Rnxx solved-41-notRNA.txt
./maximal -Rnxx solved-41-protin.txt
./maximal -Rnxx solved-42-fasta1.txt
./maximal -Rnxx solved-42-fasta2.txt


