#!/bin/bash
clear
date

# CLEAN-UP POSSIBLE DUPLICATE LINES FROM OCCASIONAL FPRINTF GLITCH
awk '!seen[$0]++' output.mha > output.log
if [ -f tricksy-output.mha ]; then
	awk '!seen[$0]++' tricksy-output.mha > tricksy-output.log
fi

rm output.mha
if [ -f tricksy-output.mha ]; then
	rm tricksy-output.mha
fi

echo 'wc output.log'
wc output.log 
echo
echo '# tests at 1000'
grep -cE '\t1000' output.log 
echo
echo 'REC:1000'
grep -cE 'C.1000' output.log 
echo
echo 'CYC:60k+'
grep -cE 'CYC.600' output.log 
echo
echo 'k=3'
grep -cE 'k=3' output.log 
echo
awk -F'[\t]' '{sum+=$4} END {print "WCR AVERAGE: " sum/NR} END {print "WCR CHECKSUM: "sum}' output.log 
echo
awk -F'[\t]' '{sum+=$9} END {print "WIDTH CHECKSUM: "sum}' output.log 
echo
echo 'head output.log'
head output.log
echo 'tail output.log'
tail output.log
