#!/bin/bash
clear
date
echo 'wc output.log'
wc output.log 
echo
echo '# tests at 1000'
grep -cE '\t1000' output.log 
echo
echo 'REC:1000'
grep -cE 'C.1000' output.log 
echo
echo 'CYC:60k+'
grep -cE 'CYC.600' output.log 
echo
echo 'k=3'
grep -cE 'k=3' output.log 
echo
awk -F'[\t]' '{sum+=$4} END {print "AVERAGE: " sum/NR} END {print "CHECKSUM: "sum}' output.log 
echo
echo 'head output.log'
head output.log
echo 'tail output.log'
tail output.log
