#!/bin/bash
	./maximal -Rn corpus/Danan_ex3.txt
	./maximal -Rn corpus/Dbipe_ex3.txt
	./maximal -Rn corpus/Dbiar_ex3.txt
	./maximal -Rn corpus/Derec_ex3.txt
	./maximal -Rn corpus/Dmela_ex3.txt
	./maximal -Rn corpus/Dsimu_ex3.txt
	./maximal -Rn corpus/Dsuzu_ex3.txt
	./maximal -Rn corpus/Dyaku_ex3.txt
	./maximal -Rn corpus/Dbiar_NEE.txt
	./maximal -Rn corpus/Derec_NEE.txt
	./maximal -Rn corpus/Dmela_NEE.txt
	./maximal -Rn corpus/Dsimu_NEE.txt
	./maximal -Rn corpus/Dsuzu_NEE.txt
	./maximal -Rn corpus/Dyaku_NEE.txt
	./maximal -Rn corpus/Dmela_DWME.txt

./script-checkmha
