#!/bin/bash
./maximal -Rna
./maximal -Rnb
./maximal -Rnc
./maximal -Rnd
./maximal -Rne
./maximal -Rnf
./maximal -Rng
./maximal -Rnh
./maximal -Rn corpus/Danan_ex3.txt
./maximal -Rn corpus/Dbipe_ex3.txt
./maximal -Rn corpus/Dbiar_ex3.txt
./maximal -Rn corpus/Derec_ex3.txt
./maximal -Rn corpus/Dmaur_ex3.txt
./maximal -Rn corpus/Dmela_ex3.txt
./maximal -Rn corpus/Dsant_ex3.txt
./maximal -Rn corpus/Dsech_ex3.txt
./maximal -Rn corpus/Dsimu_ex3.txt
./maximal -Rn corpus/Dsuzu_ex3.txt
./maximal -Rn corpus/Dyaku_ex3.txt
./maximal -Rn corpus/Dbiar_NEE.txt
./maximal -Rn corpus/Derec_NEE.txt
./maximal -Rn corpus/Dmaur_NEE.txt
./maximal -Rn corpus/Dmela_NEE.txt
./maximal -Rn corpus/Dsant_NEE.txt
./maximal -Rn corpus/Dsech_NEE.txt
./maximal -Rn corpus/Dsimu_NEE.txt
./maximal -Rn corpus/Dsuzu_NEE.txt
./maximal -Rn corpus/Dyaku_NEE.txt
./maximal -Rn corpus/Dmela_DWME.txt
./maximal -Rn corpus/solved-01-toslip_tricksy.txt
./maximal -Rn corpus/solved-02-toslip_tricksy.txt
./maximal -Rn corpus/solved-03-tosSt1_tricksy.txt
./maximal -Rn corpus/solved-04-tos-ct_tricksy.txt
./maximal -Rn corpus/solved-22-tosSt2_tricksy.txt
./maximal -Rn corpus/solved-23-tosSt2_tricksy.txt
./maximal -Rn corpus/solved-24-tosSt2_tricksy.txt
./maximal -Rn corpus/solved-25-tosSt2_tricksy.txt
./maximal -Rn corpus/solved-26-tosSt2_tricksy.txt
./maximal -Rn corpus/solved-29-toslp2_tricksy.txt
./maximal -Rn corpus/solved-30-toslp2_tricksy.txt
./maximal -Rn corpus/solved-31-t0edge_tricksy.txt
./maximal -Rn corpus/solved-44-tosimp_tricksy.txt
./maximal -Rn corpus/solved-05-koshp1_tricksy.txt
./maximal -Rn corpus/solved-06-koslip_tricksy.txt
./maximal -Rn corpus/solved-07-koslip_tricksy.txt
./maximal -Rn corpus/solved-08-koslp2_tricksy.txt
./maximal -Rn corpus/solved-09-koslp3_tricksy.txt
./maximal -Rn corpus/solved-18-koshp2_tricksy.txt
./maximal -Rn corpus/solved-19-koslp4_tricksy.txt
./maximal -Rn corpus/solved-45-cinky1_tricksy.txt
./maximal -Rn corpus/solved-46-cinky2_tricksy.txt
./maximal -Rn corpus/solved-10-cycle1_tricksy.txt
./maximal -Rn corpus/solved-11-cycle1_tricksy.txt
./maximal -Rn corpus/solved-12-cycle1_tricksy.txt
./maximal -Rn corpus/solved-13-cycle2_tricksy.txt
./maximal -Rn corpus/solved-14-cycle3_tricksy.txt
./maximal -Rn corpus/solved-15-cycle4_tricksy.txt
./maximal -Rn corpus/solved-17-cycle5_tricksy.txt
./maximal -Rn corpus/solved-47-cycle6_tricksy.txt
./maximal -Rn corpus/solved-16-cyc3_a_tricksy.txt
./maximal -Rn corpus/solved-20-cyc3_b_tricksy.txt
./maximal -Rn corpus/solved-21-cyc3_c_tricksy.txt
./maximal -Rn corpus/solved-27-cycleX_tricksy.txt
./maximal -Rn corpus/solved-49-cyctip_tricksy.txt
./maximal -Rn corpus/solved-50-cyctip_tricksy.txt
./maximal -Rn corpus/solved-51-cyctip_tricksy.txt
./maximal -Rn corpus/solved-52-cyctip_tricksy.txt
./maximal -Rn corpus/solved-32-combo1_tricksy.txt
./maximal -Rn corpus/solved-28-scrtch_tricksy.txt
./maximal -Rn corpus/solved-33-imprf1_tricksy.txt
./maximal -Rn corpus/solved-34-imprf2_tricksy.txt
./maximal -Rn corpus/solved-35-imprf3_tricksy.txt
./maximal -Rn corpus/solved-36-imprf4_tricksy.txt
./maximal -Rn corpus/solved-37-imprfk_tricksy.txt
./maximal -Rn corpus/solved-38-imprft_tricksy.txt
./maximal -Rn corpus/solved-39-imprfk_tricksy.txt
./maximal -Rn corpus/solved-40-imprfk_tricksy.txt
./maximal -Rn corpus/solved-43-timprf_tricksy.txt
./maximal -Rn corpus/solved-53-impkhp_tricksy.txt
./maximal -Rn corpus/solved-54-impkhp_tricksy.txt
./maximal -Rn corpus/solved-55-impkhp_tricksy.txt
./maximal -Rn corpus/solved-48-tbdslp_tricksy.txt
./maximal -Rn corpus/solved-56-tbslp2_tricksy.txt
./maximal -Rn corpus/solved-57-tbslp2_tricksy.txt
./maximal -Rn corpus/solved-41-RNAnuc.txt
./maximal -Rn corpus/solved-41-notRNA.txt
./maximal -Rn corpus/solved-41-protin.txt
./maximal -Rn corpus/solved-42-fasta1.txt
./maximal -Rn corpus/solved-42-fasta2.txt

