#!/bin/bash

echo 'sand dunes' >> corduroy.log
./surfboard-Pop_Up

if [ -f Surf_wavereport.mha ]; then
        rm Surf_wavereport.mha
fi

# FAVE TESTS START ON LINE 11
./maximal -DRKn  waves/tubespit/seq-017-cycle5.txt 
./maximal -DRKnC waves/tubespit/seq-017-cycle5.txt 
./maximal -DRKn waves/tubespit/seq-150-v377_cycAB1.txt 
./maximal -DRKn waves/tubespit/seq-151-v377_cycAB2.txt 
./maximal -DRKn waves/tubespit/seq-152-v377_cycAB3.txt 
./maximal -DRKn waves/tubespit/seq-153-v377_cycAB4.txt 
./maximal -DRKn waves/tubespit/seq-154-v427_cycABs.txt
./maximal -DRKn waves/tubespit/seq-000-orig_b.txt 
./maximal -DRKn waves/tubespit/seq-000-orig_c.txt 
./maximal -DRKn waves/tubespit/seq-000-orig_d.txt 
./maximal -DRKn waves/tubespit/seq-000-orig_e.txt 
./maximal -DRKn waves/tubespit/seq-000-orig_f.txt 
./maximal -DRKnx waves/tubespit/seq-033-imprf1.txt 

./surfboard-checkmha

