#!/bin/bash
echo >> Corduroy.log
echo '                                               < sand_dunes >' >> Corduroy.log

while getopts c option
do
case "${option}"
in
c) 	echo 'with fresh compile (-c)' >> Corduroy.log
	./surfboard-Pop_Up
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
        rm Surf_wavereport.mha
fi


# DIAGNOSTIC TESTS START ON LINE 21
./maximal -D 8 -KRn  waves/tubespit/seq-017-variant.txt
./maximal -D 8 -KRn  waves/tubespit/seq-017-cycle5.txt
./maximal -D 8 -KRnC waves/tubespit/seq-017-cycle5.txt
./maximal -D 8 -KRn  waves/tubespit/seq-154-v427_cycABs.txt
./maximal -D 8 -KR   waves/tubespit/seq-000-orig_b.txt 
./maximal -D 8 -KRn  waves/tubespit/seq-000-orig_c.txt 
./maximal -D 8 -KR   waves/tubespit/seq-000-orig_d.txt 
./maximal -D 8 -KR   waves/tubespit/seq-000-orig_e.txt 
./maximal -D 8 -KR   waves/tubespit/seq-000-orig_f.txt 
./maximal -D 8 -KRx  waves/tubespit/seq-033-imprf1.txt 
./maximal -D 8 -KR   waves/tubespit/seq-100-v343_10.txt 
./maximal -D 8 -KRn  waves/chowder/seq6-koslip-snippet.txt 
./maximal -D 8 -KRn  waves/chowder/abba_zabba_1.txt 
./maximal -D 8 -KRn  waves/chowder/abba_zabba_2.txt 
./maximal -D 8 -KRn  waves/chowder/abba_zabba_3.txt 
./maximal -D 8 -KRn  waves/chowder/abba_zabba_4.txt 
./maximal -D 8 -KR   waves/chowder/seq26-snippet.txt 
./maximal -D 8 -KR   waves/chowder/gal11-knot1.txt 
./maximal -D 8 -KR   waves/chowder/seq26-variations1.txt 
./maximal -D 8 -KR   waves/chowder/seq26-variations2.txt 
./maximal -D 8 -KRn  waves/chowder/snippet-jetsam-01.txt 
./maximal -D 8 -KRn  waves/chowder/snippet-jetsam-03.txt 

echo
echo
echo
echo "$0"
echo
echo
./surfboard-checkmha
echo 'Current commit WCR average of 22: 0.373591 (chowder-free)' | tee -a Corduroy.log
echo | tee -a Corduroy.log
