#!/bin/bash
echo >> Corduroy.log
echo '                                               < eat chowder cinch-k all k-mers>' >> Corduroy.log

answer="n"

while getopts c option
do
case "${option}"
in
c) 	./surfboard-Pop_Up
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
	    rm Surf_wavereport.mha
fi


	./maximal -aKR -D 8 waves/chowder/flotsam_10F.txt	# multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -aKR -D 8 waves/chowder/flotsam_14F.txt	# multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -aKR -D 8 waves/chowder/flotsam_21R.txt
	./maximal -aKR -D 8 waves/chowder/flotsam_28F.txt
	./maximal -aKR -D 8 waves/chowder/flotsam_31R.txt
	./maximal -aKR -D 8 waves/chowder/flotsam_35R.txt
	./maximal -aKR -D 8 waves/chowder/flotsam_36R.txt
	./maximal -aKR -D 8 waves/chowder/flotsam_40R.txt
	./maximal -aKR -D 8 waves/chowder/flotsam_41R.txt
	./maximal -aKR -D 8 waves/chowder/flotsam_44R.txt
	./maximal -aKR -D 8 waves/chowder/flotsam_45F.txt
	./maximal -aKR -D 8 waves/chowder/flotsam_46R.txt
	./maximal -aKR -D 8 waves/chowder/s06-k.txt
	./maximal -aKR -D 8 waves/chowder/s10-k.txt
	./maximal -aKR -D 8 waves/chowder/s14-k.txt
	./maximal -aKR -D 8 waves/chowder/s26-k.txt
	./maximal -aKR -D 8 waves/chowder/s28-k.txt
	./maximal -aKR -D 8 waves/chowder/s32-k.txt
	./maximal -aKR -D 8 waves/chowder/s36-k.txt
	./maximal -aKR -D 8 waves/chowder/s38-k.txt
	./maximal -aKR -D 8 waves/chowder/s40-k.txt
	./maximal -aKR -D 8 waves/chowder/s42-k.txt
	./maximal -aKR -D 8 waves/chowder/s44-k.txt
	./maximal -aKR -D 8 waves/chowder/s46-k.txt
	./maximal -aKR -D 8 waves/chowder/s48-k.txt
	./maximal -aKR -D 8 waves/chowder/s50-k.txt
	./maximal -aKR -D 8 waves/chowder/st08-k.txt
	./maximal -aKR -D 8 waves/chowder/st10-k.txt
	./maximal -aKR -D 8 waves/chowder/str02-k.txt
	./maximal -aKR -D 8 waves/chowder/str04-k.txt
	./maximal -aKR -D 8 waves/chowder/str06-k.txt
	./maximal -aKR -D 8 waves/chowder/stri02-k.txt
	./maximal -aKR -D 8 waves/chowder/stri04-k.txt
	./maximal -aKR -D 8 waves/chowder/stri08-k.txt
	./maximal -aKR -D 8 waves/chowder/stri10-k.txt
	./maximal -aKR -D 8 waves/chowder/stri12-k.txt
	./maximal -aKR -D 8 waves/chowder/strin02-k.txt 

./surfboard-checkmha
echo 'Previous commit WCR average of 37, allowing all k-mers in cinch-k: 0.457297' | tee -a Corduroy.log
echo | tee -a Corduroy.log
