#!/bin/bash
echo >> Corduroy.log
echo '                                               < squint -- chowder >' >> Corduroy.log

while getopts c option
do
case "${option}"
in
c) 	./surfboard-Pop_Up
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
	    rm Surf_wavereport.mha
fi

	# cinch-t originating 2-D conflict

	# cinch-l originating 2-D conflict

	# cinch-k originating 2-D conflict

	# solved: push new solved runs onto top of stack starting w/ solved-97 
	./maximal -KnxR waves/squeegee/squint_10-xb3.txt	# solved-101 another conflict calling case in mark_tela(); b3-only chowder
	./maximal -KnxR waves/squeegee/squint_07-xb3.txt	# solved-100 conflict calling in mark_tela(); b3- and b4- chowder
	./maximal -KnxR waves/squeegee/squint_11-xb3.txt	# solved-100 conflict calling in mark_tela(); b3-only chowder
	./maximal -KnxR waves/squeegee/squint_08-xb3.txt	# solved-99 Simple edit on entry into fractal splitting block; b3--b6 chowder
	./maximal -KnxR waves/squeegee/squint_09-xb3.txt	# solved-99 Simple edit on entry into fractal splitting block; b3--b6 chowder
	./maximal -KnxR waves/squeegee/squint_02-xb3.txt	# solved-98 next_k() related; previously not chowder
	./maximal -KnxR waves/squeegee/squint_03-xb3.txt	# solved-98 next_k() related; previously not chowder
	./maximal -KnxR waves/squeegee/squint_05-xb3.txt	# solved-98 next_k() related; previously not chowder
	./maximal -KnxR waves/squeegee/squint_04-xb3.txt	# solved-98 next_k() related;
	./maximal -KnxR waves/squeegee/squint_06-xb3.txt 	# solved-97 New split fractal case; previously not chowder but for unsatisfying reason
	./maximal -KnxR waves/squeegee/squint_01-xb3.txt 	# solved-97 New split fractal case;

echo
echo
echo
echo "$0"
echo
echo
./surfboard-checkmha
echo 'Commit WCR average of 11 (b=6): 0.462727 (11/11 solved)' | tee -a Corduroy.log
echo 'Commit WCR average of 11 (b=5): 0.461818 (11/11 solved)' | tee -a Corduroy.log
echo 'Commit WCR average of 11 (b=4): 0.456364 (11/11 solved)' | tee -a Corduroy.log
echo 'Commit WCR average of 11 (b=3): 0.455455 (11/11 solved)' | tee -a Corduroy.log
echo | tee -a Corduroy.log
