#!/bin/bash
echo >> Corduroy.log
echo '                                               < eat nuggets >' >> Corduroy.log

answer="n"

while getopts c option
do
case "${option}"
in
c) 	./surfboard-Pop_Up
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
	    rm Surf_wavereport.mha
fi

	# conflict begins in cinch-t
	./maximal -KR -D 8 waves/chowder/nugget-42356.txt	
	./maximal -KR -D 8 waves/chowder/nugget-00001.txt	

	# conflict begins in cinch-k
	./maximal -KR -D 8 waves/chowder/nugget-47633.txt	
	./maximal -KR -D 8 waves/chowder/nugget-50546.txt	

echo
echo
echo
echo "$0"
echo
echo
./surfboard-checkmha
echo 'Commit WCR average of 4: 0.42' | tee -a Corduroy.log
echo | tee -a Corduroy.log
