#!/bin/bash
echo >> Corduroy.log
echo '                                               < churly churly >' >> Corduroy.log

answer="n"

while getopts c option
do
case "${option}"
in
c) 	./surfboard-Pop_Up
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
	    rm Surf_wavereport.mha
fi

	# conflict begins in cinch-t
	./maximal -KR -D 8 waves/chowder/churly-05.txt	# plus recovery issue (point substitution)

	# conflict begins in cinch-k

	# solved
	./maximal -KR -D 8 waves/chowder/churly-01.txt	# solved-21 delete clear_mem module in mark_tela 
	./maximal -KR -D 8 waves/chowder/churly-02.txt	# solved-21 delete clear_mem module in mark_tela 
	./maximal -KR -D 8 waves/chowder/churly-03.txt	# solved-21 delete clear_mem module in mark_tela 
	./maximal -KR -D 8 waves/chowder/churly-04.txt	# solved-21 delete clear_mem module in mark_tela 
	./maximal -KR -D 8 waves/chowder/churly-06.txt	# solved-21 delete clear_mem module in mark_tela 
	./maximal -KR -D 8 waves/chowder/churly-07.txt	# solved-21 delete clear_mem module in mark_tela 

echo
echo
echo
echo "$0"
echo
echo
./surfboard-checkmha
echo 'Commit WCR average of 7: 0.478571 (6/7 solved)' | tee -a Corduroy.log
echo | tee -a Corduroy.log
