#!/bin/bash
./surfboard-Pop_Up

if [ -f Surf_wavereport.mha ]; then
	rm Surf_wavereport.mha
fi
if [ -f waves/foam_and_waves/foam_and_chowder.log ]; then
	rm waves/foam_and_waves/foam_and_chowder.log
fi

./maximal -Rn waves/chowder/chowder_v327_52.txt
./maximal -Rn waves/chowder/chowder_v343_01.txt
./maximal -Rn waves/chowder/chowder_v343_02.txt
./maximal -Rn waves/chowder/chowder_v343_03.txt
./maximal -Rn waves/chowder/chowder_v343_04.txt
./maximal -Rn waves/chowder/chowder_v343_05.txt
./maximal -Rn waves/chowder/chowder_v343_06.txt
./maximal -Rn waves/chowder/chowder_v343_07.txt
./maximal -Rn waves/chowder/chowder_v343_08.txt
./maximal -Rn waves/chowder/chowder_v343_09.txt
./maximal -Rn waves/chowder/chowder_v343_10.txt
./maximal -Rn waves/chowder/chowder_v343_11.txt
./maximal -Rn waves/chowder/chowder_v343_12.txt
./maximal -Rn waves/chowder/chowder_v343_13.txt
./maximal -Rn waves/chowder/chowder_v343_17.txt
./maximal -Rn waves/chowder/chowder_v343_18.txt
./maximal -Rn waves/chowder/chowder_v343_20.txt
./maximal -Rn waves/chowder/chowder_v343_21.txt
./maximal -Rn waves/chowder/chowder_v343_22.txt
./maximal -Rn waves/chowder/chowder_v343_23.txt
./maximal -Rn waves/chowder/chowder_v343_24.txt
./maximal -Rn waves/chowder/chowder_v343_25.txt
./maximal -Rn waves/chowder/chowder_v344_01.txt
./maximal -Rn waves/chowder/chowder_v344_02.txt
./maximal -Rn waves/chowder/chowder_v344_04.txt
./maximal -Rn waves/chowder/chowder_v344_07.txt
./maximal -Rn waves/chowder/chowder_v344_08.txt
./maximal -Rn waves/chowder/chowder_v344_09.txt
./maximal -Rn waves/chowder/chowder_v344_10.txt
./maximal -Rn waves/chowder/chowder_v344_12.txt
./maximal -Rn waves/chowder/chowder_v344_13.txt
./maximal -Rn waves/chowder/chowder_v344_16.txt
./maximal -Rn waves/chowder/chowder_v344_17.txt
./maximal -Rn waves/chowder/chowder_v344_18.txt
./maximal -Rn waves/chowder/chowder_v344_22.txt
./maximal -Rn waves/chowder/chowder_v344_23.txt
./maximal -Rn waves/chowder/chowder_v344_24.txt
./maximal -Rn waves/chowder/chowder_v344_25.txt
./maximal -Rn waves/chowder/chowder_v344_26.txt
./maximal -Rn waves/chowder/chowder_v344_27.txt
./maximal -Rn waves/chowder/chowder_v344_28.txt
./maximal -Rn waves/chowder/chowder_v344_29.txt
./maximal -Rn waves/chowder/chowder_v344_30.txt
./maximal -Rn waves/chowder/chowder_v344_33.txt
./maximal -Rn waves/chowder/chowder_v344_34.txt

./surfboard-checkmha

