#!/bin/bash
echo >> Corduroy.log
echo '                                               < eatchowder >' >> Corduroy.log


while getopts c option
do
case "${option}"
in
c) 	./surfboard-Pop_Up
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
        rm Surf_wavereport.mha
fi

# Solved but leaving here as a temporary record:
./maximal -D 8 -KRn waves/chowder/flotsam_06F.txt
./maximal -D 8 -KRn waves/chowder/flotsam_09F.txt
./maximal -D 8 -KRn waves/chowder/flotsam_15F.txt
./maximal -D 8 -KRn waves/chowder/flotsam_16F.txt
./maximal -D 8 -KRn waves/chowder/flotsam_22R.txt
./maximal -D 8 -KRn waves/chowder/flotsam_26R.txt
./maximal -D 8 -KRn waves/chowder/flotsam_27R.txt
./maximal -D 8 -KRn waves/chowder/flotsam_32R.txt
./maximal -D 8 -KRn waves/chowder/flotsam_33F.txt
./maximal -D 8 -KRn waves/chowder/flotsam_38F.txt

# EXTANT CHOWDER STARTS BELOW
./maximal -D 8 -KRn waves/chowder/jetsam-04-Dsuz_vnd_NEE_FY-100mer.txt 
./maximal -D 8 -KRn waves/chowder/jetsam-05-Dana_vnd_ex3_FY-100mer.txt 
./maximal -D 8 -KRn waves/chowder/snippet-jetsam-05.txt
./maximal -D 8 -KRn waves/chowder/flotsam_01F.txt
./maximal -D 8 -KRn waves/chowder/flotsam_02F.txt
./maximal -D 8 -KRn waves/chowder/flotsam_03F.txt
./maximal -D 8 -KRn waves/chowder/flotsam_04F.txt
./maximal -D 8 -KRn waves/chowder/flotsam_05F.txt
./maximal -D 8 -KRn waves/chowder/flotsam_07F.txt
./maximal -D 8 -KRn waves/chowder/flotsam_08F.txt
./maximal -D 8 -KRn waves/chowder/flotsam_10F.txt
./maximal -D 8 -KRn waves/chowder/flotsam_11F.txt
./maximal -D 8 -KRn waves/chowder/flotsam_12F.txt
./maximal -D 8 -KRn waves/chowder/flotsam_13F.txt
./maximal -D 8 -KRn waves/chowder/flotsam_14F.txt
./maximal -D 8 -KRn waves/chowder/flotsam_17F.txt
./maximal -D 8 -KRn waves/chowder/flotsam_18F.txt
./maximal -D 8 -KRn waves/chowder/flotsam_19F.txt
./maximal -D 8 -KRn waves/chowder/flotsam_20R.txt
./maximal -D 8 -KRn waves/chowder/flotsam_21R.txt
./maximal -D 8 -KRn waves/chowder/flotsam_23R.txt
./maximal -D 8 -KRn waves/chowder/flotsam_24R.txt
./maximal -D 8 -KRn waves/chowder/flotsam_25R.txt
./maximal -D 8 -KRn waves/chowder/flotsam_28F.txt
./maximal -D 8 -KRn waves/chowder/flotsam_29R.txt
./maximal -D 8 -KRn waves/chowder/flotsam_30R.txt
./maximal -D 8 -KRn waves/chowder/flotsam_31R.txt
./maximal -D 8 -KRn waves/chowder/flotsam_34R.txt
./maximal -D 8 -KRn waves/chowder/flotsam_35R.txt
./maximal -D 8 -KRn waves/chowder/flotsam_36R.txt
./maximal -D 8 -KRn waves/chowder/flotsam_37F.txt
./maximal -D 8 -KRn waves/chowder/flotsam_39F.txt

./surfboard-checkmha
