#!/bin/bash
echo >> Corduroy.log
echo '                                               < churly churly >' >> Corduroy.log

while getopts c option
do
case "${option}"
in
c) 	./surfboard-Pop_Up
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
	    rm Surf_wavereport.mha
fi

	# conflict begins in cinch-t

	# conflict begins in cinch-k

	# solved
	./maximal -KR -D 8 waves/chowder/churly-01.txt	# solved-21 delete clear_mem module in mark_tela 
	./maximal -KR -D 8 waves/chowder/churly-02.txt	# solved-21 delete clear_mem module in mark_tela 
	./maximal -KR -D 8 waves/chowder/churly-03.txt	# solved-21 delete clear_mem module in mark_tela 
	./maximal -KR -D 8 waves/chowder/churly-04.txt	# solved-21 delete clear_mem module in mark_tela 
	./maximal -KR -D 8 waves/chowder/churly-06.txt	# solved-21 delete clear_mem module in mark_tela 
	./maximal -KR -D 8 waves/chowder/churly-07.txt	# solved-21 delete clear_mem module in mark_tela 
	./maximal -KR -D 8 waves/chowder/churly-05.txt	# solved-22 adjustment to cyclelize_tela()
	./maximal -KR -D 8 waves/chowder/churly-09.txt	# solved-22 adjustment to cyclelize_tela()
	./maximal -KR -D 8 waves/chowder/churly-08.txt	# solved-23 new cinch-k low-complexity block
	./maximal -KR -D 8 waves/chowder/churly-10.txt	# solved-24 adjustment to new low-complexity block in cinch-k
													# solved-25--26 -> PISO4 script
	./maximal -KR -D 8 waves/chowder/churly-11.txt	# solved-27 new cinch-k cluster-f*ck block
	./maximal -KR -D 8 waves/chowder/churly-12.txt	# solved-28 slight adjustment to new cinch-k block of solved-27
	./maximal -KR -D 8 waves/chowder/churly-13.txt	# solved-28 slight adjustment to new cinch-k block of solved-27
	./maximal -KR -D 8 waves/chowder/churly-14.txt	# solved-29 new mark_tela() block for conflict marking
	./maximal -KR -D 8 waves/chowder/churly-15.txt	# solved-29 new mark_tela() block for conflict marking
	./maximal -KR -D 8 waves/chowder/churly-16.txt	# solved-30 adjustment for new cinch-k block of solved 27-28

echo
echo
echo
echo "$0"
echo
echo
./surfboard-checkmha
echo 'Commit WCR average of 16: 0.455 (chowder-free)' | tee -a Corduroy.log
echo | tee -a Corduroy.log
