#!/bin/bash
echo >> corduroy.log
echo 'Sand dunes:' >> corduroy.log

while getopts c option
do
case "${option}"
in
c) 	echo 'with fresh compile (-c)' >> corduroy.log
	./surfboard-Pop_Up
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
        rm Surf_wavereport.mha
fi


# DIAGNOSTIC TESTS START ON LINE 21
./maximal -DKR  waves/tubespit/seq-017-variant.txt
./maximal -DKR  waves/tubespit/seq-017-cycle5.txt
./maximal -DKRC waves/tubespit/seq-017-cycle5.txt
./maximal -DKR  waves/tubespit/seq-154-v427_cycABs.txt
./maximal -DKR  waves/tubespit/seq-000-orig_b.txt 
./maximal -DKR  waves/tubespit/seq-000-orig_c.txt 
./maximal -DKR  waves/tubespit/seq-000-orig_d.txt 
./maximal -DKR  waves/tubespit/seq-000-orig_e.txt 
./maximal -DKR  waves/tubespit/seq-000-orig_f.txt 
./maximal -DKRx waves/tubespit/seq-033-imprf1.txt 
./maximal -DKR  waves/tubespit/seq-100-v343_10.txt 
./maximal -DKR  waves/chowder/seq6-koslip-snippet.txt 
./maximal -DKR  waves/chowder/abba_zabba_1.txt 
./maximal -DKR  waves/chowder/abba_zabba_2.txt 
./maximal -DKR  waves/chowder/abba_zabba_3.txt 
./maximal -DKR  waves/chowder/abba_zabba_4.txt 
./maximal -DKR  waves/chowder/seq26-snippet.txt 
./maximal -DKR  waves/chowder/gal11-knot1.txt 
./maximal -DKR  waves/chowder/seq26-variations1.txt 
./maximal -DKR  waves/chowder/seq26-variations2.txt 

./surfboard-checkmha
echo 'sand_dunes benchmark WCR average of 20: 0.37815' | tee -a corduroy.log
echo
