#!/bin/bash

echo '                                               < Fisher-Yates D. mel. vnd NEE core >' >> Corduroy.log

if [ ! -f lineup ]; then
	./surfboard-Pop_Up
fi
if [ -f Surf_wavereport.mha ]; then
        rm Surf_wavereport.mha
fi

for i in {1..1000}
do
	./lineup -Rn -X 2 -Y 640 waves/2019a/vnd_intronic-func_Dmel.txt
done

./surfboard-checkmha

