#!/bin/bash
echo >> Corduroy.log
echo '                                               < squeegee >' >> Corduroy.log

while getopts c option
do
case "${option}"
in
c) 	./surfboard-Pop_Up
	grep 'define PISO' src/microhom-skor.h | tee -a Corduroy.log
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
	    rm Surf_wavereport.mha
fi

	# conflict begins in cinch-t, w/ good recovery
	 ./maximal -KRx -D 2 waves/squeegee/squee006.txt
	 ./maximal -KRx -D 2 waves/squeegee/squee010.txt

	# conflict begins in cinch-k
	 ./maximal -KRx -D 4 waves/squeegee/squee004.txt	# multi-PISO chowder
	 ./maximal -KRx -D 4 waves/squeegee/squee005.txt
	 ./maximal -KRx -D 4 waves/squeegee/squee009.txt
	 ./maximal -KRx -D 4 waves/squeegee/squee002.txt
	 ./maximal -KRx -D 4 waves/squeegee/squee007.txt
	 ./maximal -KRx -D 4 waves/squeegee/squee001.txt
	 ./maximal -KRx -D 4 waves/squeegee/squee003.txt

	# solved, start at solved-41
	 ./maximal -KRx -D 2 waves/squeegee/squee112.txt	# solved-41 rewrite of check sub-threshold fractals and k mod 3 gating
	 ./maximal -KRx -D 4 waves/squeegee/squee008.txt	# solved-41 rewrite of check sub-threshold fractals and k mod 3 gating
	 ./maximal -KRx -D 4 waves/squeegee/squee282.txt	# solved-41 rewrite of check sub-threshold fractals and k mod 3 gating
	 ./maximal -KRx -D 2 waves/squeegee/squee216.txt	# solved-42 squash imperfect k-mer that is a multiple of underlying imperfect TR
	 ./maximal -KRx -D 2 waves/squeegee/squee224.txt	# solved-43 needed extra condition for calling parents and fractals pushmem 4

echo
echo
echo
echo "$0"
echo
echo
./surfboard-checkmha
echo 'Commit WCR average of 14 (PISO=6): 0.466429 (13/14 solved)' | tee -a Corduroy.log
echo 'Commit WCR average of 14 (PISO=5): 0.477143 (10/14 solved)' | tee -a Corduroy.log
echo 'Commit WCR average of 14 (PISO=4): 0.466429 ( 8/14 solved)' | tee -a Corduroy.log
echo 'Commit WCR average of 14 (PISO=3): 0.460714 ( 5/14 solved)' | tee -a Corduroy.log
echo | tee -a Corduroy.log
