#!/bin/bash
echo >> Corduroy.log
echo '                                               < squirt chowder >' >> Corduroy.log

while getopts c option
do
case "${option}"
in
c) 	./surfboard-Pop_Up
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
	    rm Surf_wavereport.mha
fi

	# cinch-t originating 2-D conflict

	# cinch-l originating 2-D conflict

	# cinch-k originating 2-D conflict

	# solved: push new solved runs onto top of stack starting w/ solved-64 
	./maximal -KnxR waves/squeegee/squirt_39-b3.txt		# solved-95 Fixed bug in mark_tela (not setting Dtr to 0 in imperfect checks); b3--b6
	./maximal -KnxR waves/squeegee/squirt_38-b3.txt		# solved-94 Deletion of block in mark_tela(); b3--b6
	./maximal -KnxR waves/squeegee/squirt_37-b3.txt		# solved-93 Needed consensus row updating after cinch_l; -x b3-only
	./maximal -KnxR waves/squeegee/squirt_35-b4.txt		# solved-92 Cancel imperfect if adjacent column perfect; -x b4- & b5- only
	./maximal -KnxR waves/squeegee/squirt_36-b4.txt		# solved-92 Cancel imperfect if adjacent column perfect; -x b3--b5
	./maximal -KnxR waves/squeegee/squirt_34-b4.txt		# solved-91 Cancel imperfect islands if overlap w/ perfect column k-mer > k/2; -x chow at b3--b6
	./maximal -KnxR waves/squeegee/squirt_33-b4.txt		# solved-90 Generalizing framerow checking for cycle numbering in cinch_t; -x chow at b3- & b4- only
	./maximal -KnxR waves/squeegee/squirt_32-b4.txt		# solved-89 Generalizing k==1 block in cinch_k to k<=opt_b.val; b3--b5
	./maximal -KnxR waves/squeegee/squirt_31-b3.txt		# solved-88 Edit in next_k() call in mark_tela, imperfect mod k case; b3-only 
	./maximal -KnxR waves/squeegee/squirt_22-b3.txt		# solved-87 Fractals w/ fractals case, edits in mark_tela & cinch_k; b3--b6, chowder in prev versions
	./maximal -KnxR waves/squeegee/squirt_29-b6.txt		# solved-86 mark_tela(); -x b3--b6, chowder in prev versions
	./maximal -KnxR waves/squeegee/squirt_30-b6.txt		# solved-86 mark_tela(); -x b3--b6, chowder in prev versions; homologically related to _29
	./maximal -KnxR waves/squeegee/squirt_20-b3.txt		# solved-86 mark_tela(); b3- & b4- only
	./maximal -KnxR waves/squeegee/squirt_25-b3.txt		# solved-86 mark_tela(); b3- & b4- only
	./maximal -KnxR waves/squeegee/squirt_19-b3.txt		# solved-86 mark_tela(); b3-only
	./maximal -KnxR waves/squeegee/squirt_24-b3.txt		# solved-86 mark_tela(); b3-only
	./maximal -KnxR waves/squeegee/squirt_17-b3.txt		# solved-85 New mark_tela block in last position; b3--b6
	./maximal -KnxR waves/squeegee/squirt_23-b3.txt		# solved-84 Expanded mark_tela block to cancel imperfect_TR given perfect island peak; b3--b5
	./maximal -KnxR waves/squeegee/squirt_18-b3.txt		# solved-83 Fractal splitting entry edit so not dependent on Fractal cycling island extending to m; b3-only
														# partial solution; will wait until this comes up again before generalizing to all columns prior to m.
	./maximal -KnxR waves/squeegee/squirt_28-b6.txt		# solved-82 Edit to mark_tela() mod-test case; b3--b6, chowder in previous versions 
	./maximal -KnxR waves/squeegee/squirt_27-b6.txt		# solved-81 Fractal splitting -> edit in TR numbering in cinch_t(); b3--b6, not chowder in previous versions
	./maximal -KnxR waves/squeegee/squirt_16-b3.txt		# solved-80 imperfect_TR canceling in mark_tela() given perfect k-mer at k1; b3-only REC<1000
	./maximal -KnxR waves/squeegee/squirt_26-b3.txt		# solved-80 imperfect_TR canceling in mark_tela() given perfect k-mer at k1; b3-only
	./maximal -KnxR waves/squeegee/squirt_21-b3.txt		# solved-79 Fractal splitting edit in mark_tela w/ imperfect parent; b3--b5
	./maximal -KnxR waves/squeegee/squirt_15-b6.txt		# solved-78 Adjustment to next_k() missing break or return w/ transit counting; -b4--6 -x chowder
	./maximal -KnxR waves/squeegee/squirt_14-b6.txt		# solved-77 Replace OFF w/ fract check for block 12 in mark_tela(); -b4--6 -x chowder
	./maximal -KnxR waves/squeegee/squirt_13-b6.txt		# solved-76 edits in mark_tela() next_k() call and in checkfractals_in_imperfect
	./maximal -KnxR waves/squeegee/squirt_12a-b6.txt	# solved-75 new fractstat check in cinch_k
	./maximal -KnxR waves/squeegee/squirt_12b-b6.txt	# solved-75 new fractstat check in cinch_k
	./maximal -KnxR waves/squeegee/squirt_12c-b6.txt	# solved-75 new fractstat check in cinch_k
	./maximal -KnxR waves/squeegee/squirt_11-b6.txt		# solved-74 single-line edit to mha.c; b6-only chowder with both v4.34-lcl-09 and v4.35
	./maximal -KnxR waves/squeegee/squirt_10-b6.txt		# solved-73b: edits in cinch_k() after removing deprecated (redundant) blocks
														# solved-73a: solved at b=6, but new chowder at b=3-only; b6 non-chowder with v4.34-lcl-09
	./maximal -KnxR waves/squeegee/squirt_09-b6.txt		# solved-72 mark_tela() edits; b3--6
	./maximal -KnxR waves/squeegee/squirt_08-b6.txt		# solved-71 hack mark_tela() edit w/ MAGIC # k-mer size condition; b3--6
	./maximal -KnxR waves/squeegee/squirt_07-b6.txt		# solved-70 muting deprecated code in mark_tela(); b3--6
	./maximal -KnxR waves/squeegee/squirt_06-b6.txt		# solved-69 sub-threshold fractals condition to skip if next parent column is perfect k; b3--6
	./maximal -KnxR waves/squeegee/squirt_05-b6.txt		# solved-68 mark_tela edits continued again; b4--6
	./maximal -KnxR waves/squeegee/squirt_04-b6.txt		# solved-67 mark_tela edits continued; b3--6
	./maximal -KnxR waves/squeegee/squirt_03-b6.txt		# solved-66 mark_tela edits; b4-6
	./maximal -KnxR waves/squeegee/squirt_02-b6.txt		# solved-65 delete all_S condition in split fractals module of mark_tela(); b3-6
	./maximal -KnxR waves/squeegee/squirt_01-b6.txt		# solved-64 new module in mark_tela concerning cycling islands w/ perfect and imperfect columns b3-6

echo
echo
echo
echo "$0"
echo
echo
./surfboard-checkmha
echo 'Commit WCR average of 41 (b=6): 0.493415 (41/41 solved)' | tee -a Corduroy.log
echo 'Commit WCR average of 41 (b=5): 0.490976 (41/41 solved)' | tee -a Corduroy.log
echo 'Commit WCR average of 41 (b=4): 0.486341 (41/41 solved)' | tee -a Corduroy.log
echo 'Commit WCR average of 41 (b=3): 0.464878 (41/41 solved)' | tee -a Corduroy.log
echo | tee -a Corduroy.log
