#!/bin/bash
echo >> Corduroy.log
echo '                                               < squint -- chowder >' >> Corduroy.log

while getopts c option
do
case "${option}"
in
c) 	./surfboard-Pop_Up
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
	    rm Surf_wavereport.mha
fi

	# cinch-t originating 2-D conflict
	./maximal -KnxR -D8 waves/squeegee/squint_15-xb3.txt	# ; washmach chowder (1a 20% GC source) -b--6
	./maximal -KnxR -D8 waves/squeegee/squint_16-xb3.txt	# ; washmach chowder (2a 50% GC source) -b--6; split second pair to squint_15

	# cinch-l originating 2-D conflict

	# cinch-k originating 2-D conflict

	# solved: push new solved runs onto top of stack starting w/ solved-97 
	./maximal -KnxR waves/squeegee/squint_14-xb3.txt 	# solved-104 Conditioning entry into cyclelize from cinch_t; -x b3- & b4- only washing_machine chowder
	./maximal -KnxR waves/squeegee/squint_13-xb3.txt	# solved-103 Edits in fractal splitting w/ reorganization; -x b3-only chowder (mined at 1/240k b=3)
	./maximal -KnxR waves/squeegee/squirt_41-b3.txt 	# solved-102 New cinch_t block of some future cinch_k in last unit; -b3--6 vnd_ragdoll chowder
	./maximal -KnxR waves/squeegee/squirt_42-b3.txt 	# solved-102 New cinch_t block of some future cinch_k in last unit; -x, -b3--6 vnd_ragdoll chowder
	./maximal -KnxR waves/squeegee/squint_12-xb3.txt	# solved-102 New cinch_t block of some future cinch_k in last unit; -b3--6 washing_machine chowder
	./maximal -KnxR waves/squeegee/squint_10-xb3.txt	# solved-101 another conflict calling case in mark_tela(); b3-only chowder
	./maximal -KnxR waves/squeegee/squint_07-xb3.txt	# solved-100 conflict calling in mark_tela(); b3- and b4- chowder
	./maximal -KnxR waves/squeegee/squint_11-xb3.txt	# solved-100 conflict calling in mark_tela(); b3-only chowder
	./maximal -KnxR waves/squeegee/squint_08-xb3.txt	# solved-99 Simple edit on entry into fractal splitting block; b3--b6 chowder
	./maximal -KnxR waves/squeegee/squint_09-xb3.txt	# solved-99 Simple edit on entry into fractal splitting block; b3--b6 chowder
	./maximal -KnxR waves/squeegee/squint_02-xb3.txt	# solved-98 next_k() related; previously not chowder
	./maximal -KnxR waves/squeegee/squint_03-xb3.txt	# solved-98 next_k() related; previously not chowder
	./maximal -KnxR waves/squeegee/squint_05-xb3.txt	# solved-98 next_k() related; previously not chowder
	./maximal -KnxR waves/squeegee/squint_04-xb3.txt	# solved-98 next_k() related;
	./maximal -KnxR waves/squeegee/squint_06-xb3.txt 	# solved-97 New split fractal case; previously not chowder but for unsatisfying reason
	./maximal -KnxR waves/squeegee/squint_01-xb3.txt 	# solved-97 New split fractal case;

echo
echo
echo
echo "$0"
echo
echo
./surfboard-checkmha
echo 'Commit WCR average of 16 (b=6): 0.4725   (16/16 solved)' | tee -a Corduroy.log
echo 'Commit WCR average of 16 (b=5): 0.471875 (16/16 solved)' | tee -a Corduroy.log
echo 'Commit WCR average of 16 (b=4): 0.45625  (16/16 solved)' | tee -a Corduroy.log
echo 'Commit WCR average of 16 (b=3): 0.45375  (16/16 solved)' | tee -a Corduroy.log
echo | tee -a Corduroy.log
