#!/bin/bash
if [ -f Surf_wavereport.mha ]; then
        rm Surf_wavereport.mha
fi

for i in {1..1000}
do
	./maximal -RnXXY 640 waves/2019a/vnd_intronic-func_Dmel.txt
done

./surfboard-checkmha

grep -c XX vnd_intronic-func_Dmel.txt
