#!/bin/bash
echo >> Corduroy.log
echo '                                               < eat chowder 3: last five nudgings from cinch-k all k-mers, whittled >' >> Corduroy.log

answer="n"

while getopts c option
do
case "${option}"
in
c) 	./surfboard-Pop_Up
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
	    rm Surf_wavereport.mha
fi


	./maximal -aKR -D 8 waves/chowder/snippet-s32-k.txt
	./maximal -aKR -D 8 waves/chowder/snippet-s42-k.txt
	./maximal -aKR -D 8 waves/chowder/snippet-str06-k.txt
	./maximal -aKR -D 8 waves/chowder/snippet-s40-k.txt
	./maximal -aKR -D 8 waves/chowder/snippet-stri04-k.txt

./surfboard-checkmha
echo 'Commit WCR average of 5, allowing all k-mers in cinch-k: 0.3888 (5 nudgings)' | tee -a Corduroy.log
echo | tee -a Corduroy.log
