#!/bin/bash
echo >> Corduroy.log
echo '                                               < CHOWDER TESTS AT PISO = 4 >' >> Corduroy.log

while getopts c option
do
case "${option}"
in
c) 	./surfboard-Pop_Up
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
	    rm Surf_wavereport.mha
fi

	# conflict begins in cinch-t
	./maximal -KR -D 8 -x  waves/tubespit/seq-129-v344_16.txt
	./maximal -KR -D 8 -xC waves/tubespit/seq-129-v344_16.txt

	# conflict begins in cinch-k
	./maximal -KR -D 8 -x  waves/sharks/vnd_NEE_Dsuzu.txt
	./maximal -KR -D 8 -xC waves/tubespit/seq-052-cyctip.txt

	# solved
	./maximal -KR -D 8     waves/chowder/nugget-00005.txt	# solved-25 distinguishing +/- opt_x cases for next_k() as it involves PISO

echo
echo
echo
echo "$0"
echo
echo
./surfboard-checkmha
echo 'Commit WCR average of 5: 0.4916 (0/5)' | tee -a Corduroy.log
echo | tee -a Corduroy.log
