#!/bin/bash

echo '                                               < Fisher-Yates D. mel. vnd NEE flank >' >> Corduroy.log

if [ -f Surf_wavereport.mha ]; then
        rm Surf_wavereport.mha
fi

for i in {1..1000}
do
	./maximal -Rn -X 2 -Y 500 waves/2019a/vnd_intronic-nonfunc1_Dmel.txt
done

./surfboard-checkmha

