#!/bin/bash

while getopts c option
do
case "${option}"
in
c) 	./surfboard-Pop_Up
	;;
esac
done

if [ ! -f lineup ]; then
	./surfboard-Pop_Up
fi
if [ -f Surf_wavereport.mha ]; then
	    rm Surf_wavereport.mha
fi

# -D# 0=default; 1=1D; 2=cinch-t; 3=cinch-l; 4=cinch-k; 5=cinch-d; 6=relax2D; 7= pause at end of run

./lineup -Kx -D7     waves/demo_corpus/demo_01a.txt
./lineup -Kx -D7     waves/demo_corpus/demo_01b.txt
./lineup -Kx -D7     waves/demo_corpus/demo_01c.txt
./lineup -Kx -D7     waves/demo_corpus/demo_01d.txt
./lineup -Kx -D7     waves/demo_corpus/demo_01e.txt
./lineup -Kx -D7     waves/demo_corpus/demo_01f.txt
./lineup -Kx -D7 -C  waves/demo_corpus/demo_01a.txt
./lineup -Kx -D7 -C  waves/demo_corpus/demo_01b.txt
./lineup -Kx -D7 -C  waves/demo_corpus/demo_01c.txt
./lineup -Kx -D7 -C  waves/demo_corpus/demo_01d.txt
./lineup -Kx -D7 -C  waves/demo_corpus/demo_01e.txt
./lineup -Kx -D7 -C  waves/demo_corpus/demo_01f.txt
./lineup -Kx -D7     waves/demo_corpus/demo_02a.txt
./lineup -Kx -D7     waves/demo_corpus/demo_02b.txt
./lineup -Kx -D7     waves/demo_corpus/demo_02c.txt
./lineup -Kx -D7     waves/demo_corpus/demo_02d.txt
./lineup -Kx -D7     waves/demo_corpus/demo_02e.txt
./lineup -Kx -D7     waves/demo_corpus/demo_02f.txt
./lineup -Kx -D7     waves/demo_corpus/demo_02a.txt
./lineup -Kx -D7     waves/demo_corpus/demo_03b.txt
./lineup -Kx -D7     waves/demo_corpus/demo_03c.txt
./lineup -Kx -D7     waves/demo_corpus/demo_03d.txt
./lineup -Kx -D7     waves/demo_corpus/demo_03e.txt
./lineup -Kx -D7     waves/demo_corpus/demo_03f.txt
./lineup -Kx -D7     waves/demo_corpus/demo_04.txt
./lineup -Kxk        waves/demo_corpus/kmer_mod3_counting.txt
