#!/bin/bash

echo '                                               < vnd_getworked_clean >' >> Corduroy.log

if [ ! -f lineup ]; then
	./surfboard-Pop_Up
fi
if [ -f Surf_wavereport.mha ]; then
        rm Surf_wavereport.mha
fi
	./lineup -Rn waves/seals/vnd_ex3_Dmela.txt
	./lineup -Rn waves/seals/vnd_ex3_Dsimu.txt
	./lineup -Rn waves/seals/vnd_ex3_Derec.txt
	./lineup -Rn waves/seals/vnd_ex3_Dyaku.txt
	./lineup -Rn waves/seals/vnd_ex3_Dbiar.txt
	./lineup -Rn waves/seals/vnd_ex3_Dsuzu.txt
	./lineup -Rn waves/seals/vnd_ex3_Danan.txt
	./lineup -Rn waves/seals/vnd_ex3_Dbipe.txt
	./lineup -Rn waves/sharks/vnd_NEE_Dmela.txt
	./lineup -Rn waves/sharks/vnd_NEE_Dsimu.txt
	./lineup -Rn waves/sharks/vnd_NEE_Derec.txt
	./lineup -Rn waves/sharks/vnd_NEE_Dyaku.txt
	./lineup -Rn waves/sharks/vnd_NEE_Dbiar.txt
	./lineup -Rn waves/sharks/vnd_NEE_Dsuzu.txt
	./lineup -Rn waves/sharks/nab_DWME_Dmela.txt

./surfboard-checkmha
echo 'WCR avg history (15 tests @ b=3): 0.4794 ->0.471133 ->0.471933 ->0.4722' | tee -a Corduroy.log
echo | tee -a Corduroy.log
