#!/bin/bash
echo >> Corduroy.log
echo '                                               < fractal_splitting >' >> Corduroy.log

while getopts c option
do
case "${option}"
in
c) 	echo 'with fresh compile (-c)' >> Corduroy.log
	./surfboard-Pop_Up
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
        rm Surf_wavereport.mha
fi


# DIAGNOSTIC TESTS START ON LINE 21
./maximal  -KnR -D 8 waves/chowder/seq26-snippet.txt 
./maximal  -KnR -D 8 waves/chowder/gal11-knot1.txt 
./maximal  -KnR -D 8 waves/chowder/seq26-variations1.txt 
./maximal  -KnR -D 8 waves/chowder/seq26-variations2.txt 
./maximal  -KnR -D 8 waves/chowder/snippet-string02-t.txt
./maximal  -KnR -D 8 waves/chowder/snippet-seq-014-cycle3.txt 

echo
echo
echo
echo "$0"
echo
echo
./surfboard-checkmha
echo 'Current commit WCR average of 6 (PISO = 5|4|3): 0.372 (chowder-free)' | tee -a Corduroy.log

echo | tee -a Corduroy.log
