#!/bin/bash
./maximal -OOn  waves/shark_vnd_edgeNEE_Dmaur.txt 
./maximal -OOn  waves/shark_vnd_edgeNEE_Dsimu.txt 

rm Surf_wavereport.mha

# ./maximal -OOnx waves/shark_vnd_edgeNEE_Dmaur.txt 
# ./maximal -OOnx waves/shark_vnd_edgeNEE_Dsimu.txt 
