#!/bin/bash
echo >> Corduroy.log
echo '                                               < fractal_splitting >' >> Corduroy.log

while getopts c option
do
case "${option}"
in
c) 	echo 'with fresh compile (-c)' >> Corduroy.log
	./surfboard-Pop_Up
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
        rm Surf_wavereport.mha
fi


# DIAGNOSTIC TESTS START ON LINE 21
./maximal -D 8 -KR   waves/chowder/seq26-snippet.txt 
./maximal -D 8 -KR   waves/chowder/gal11-knot1.txt 
./maximal -D 8 -KR   waves/chowder/seq26-variations1.txt 
./maximal -D 8 -KR   waves/chowder/seq26-variations2.txt 
./maximal -D 8 -KRn  waves/chowder/snippet-string02-t.txt
./maximal -D 8 -KRn  waves/chowder/snippet-seq-014-cycle3.txt 

./surfboard-checkmha
echo 'fractal_splitting benchmark WCR average of 6: 0.372' | tee -a Corduroy.log
echo | tee -a Corduroy.log
