#!/bin/bash
echo >> Corduroy.log
echo '                                               < chowder 2: three snippet test cases >' >> Corduroy.log

answer="n"

while getopts c option
do
case "${option}"
in
c) 	./surfboard-Pop_Up
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
	    rm Surf_wavereport.mha
fi


	./maximal -KR waves/chowder/snippet-flotsam_10F.txt
	./maximal -KR waves/chowder/snippet-flotsam_14F.txt
	./maximal -KR waves/chowder/snippet-flotsam_21R.txt

echo
echo
echo
echo "$0"
echo
echo
./surfboard-checkmha
echo 'Commit WCR average of three: 0.537667' | tee -a Corduroy.log
echo | tee -a Corduroy.log
