#!/bin/bash
echo >> Corduroy.log
echo '                                               < chowder 3: last nudgings from cinch-k all k-mers, whittled >' >> Corduroy.log

answer="n"

while getopts c option
do
case "${option}"
in
c) 	./surfboard-Pop_Up
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
	    rm Surf_wavereport.mha
fi


	./maximal -KR -D 8 waves/chowder/snippet-s32-k.txt		# solved-12
	./maximal -KR -D 8 waves/chowder/snippet-s42-k.txt		# solved-12
	./maximal -KR -D 8 waves/chowder/snippet-str06-k.txt	# solved-12
	./maximal -KR -D 8 waves/chowder/snippet-stri04-k.txt	# solved-12
	./maximal -KR -D 8 waves/chowder/snippet-s40-k.txt		# solved-13

./surfboard-checkmha
echo 'Commit WCR average of 5, allowing all k-mers in cinch-k: 0.372' | tee -a Corduroy.log
echo | tee -a Corduroy.log
