#!/bin/bash
echo >> Corduroy.log
echo '                                               < squeegee: PISO 3 -x chowder >' >> Corduroy.log

while getopts c option
do
case "${option}"
in
c) 	./surfboard-Pop_Up
	grep 'define PISO' src/microhom-skor.h | tee -a Corduroy.log
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
	    rm Surf_wavereport.mha
fi

	# conflict begins in cinch-t

	# conflict begins in cinch-k
	./maximal -KRx -D 8 waves/squeegee/squee024.txt		# chowder at P 3--6

	# solved, start at solved-41
	./maximal -KRx waves/squeegee/squee112.txt		# solved-41 rewrite of check sub-threshold fractals and k mod 3 gating
	./maximal -KRx waves/squeegee/squee008.txt		# solved-41 rewrite of check sub-threshold fractals and k mod 3 gating
	./maximal -KRx waves/squeegee/squee282.txt		# solved-41 rewrite of check sub-threshold fractals and k mod 3 gating
	./maximal -KRx waves/squeegee/squee216.txt		# solved-42 squash imperfect k-mer that is a multiple of underlying imperfect TR
	./maximal -KRx waves/squeegee/squee224.txt		# solved-43 needed extra condition for calling parents and fractals pushmem 4; 7286 lines
	./maximal -KRx waves/squeegee/squee006.txt		# solved-45 add'l block for sub-threshold fractals in mark_tela(); 7300 lines
	./maximal -KRx waves/squeegee/squee004.txt		# solved-46 multi-PISO chowder, cinch-k tela logic conversion of nuctransit check; 7300 lines
	./maximal -KRx waves/squeegee/squee009.txt		# solved-47 deleted wonky check transit block in cinch-k; solved 4/14 squee; 7300 lines
	./maximal -KRx waves/squeegee/squee007.txt		# solved-47 deleted wonky check transit block in cinch-k; solved 4/14 squee; 7300 lines
	./maximal -KRx waves/squeegee/squee001.txt		# solved-47 deleted wonky check transit block in cinch-k; solved 4/14 squee; 7300 lines
	./maximal -KRx waves/squeegee/squee003.txt		# solved-47 deleted wonky check transit block in cinch-k; solved 4/14 squee; 7300 lines
	./maximal -KRx waves/squeegee/squee002.txt		# solved-48 condition a cinch-k block to only k>1; 7298 lines
	./maximal -KRx waves/squeegee/squee005.txt		# solved-48 condition a cinch-k block to only k>1; 7298 lines
	./maximal -KRx waves/squeegee/squee010.txt		# solved-44 allowing fractal call based on k1 in addition to ok; 7286 lines
													# re-appeared for PISO 4 and 5 with solved-46; different issue; captured in same snippet
													# solved-49 new k=1 block in cinch-k based on unshifted consensus row; 7302 lines
	./maximal -KRx waves/squeegee/squee011.txt		# already solved
	./maximal -KRx waves/squeegee/squee012.txt		# already solved
	./maximal -KRx waves/squeegee/squee013.txt		# already solved
	./maximal -KRx waves/squeegee/squee014.txt		# already solved
	./maximal -KRx waves/squeegee/squee016.txt		# already solved
	./maximal -KRx waves/squeegee/squee017.txt		# already solved
	./maximal -KRx waves/squeegee/squee019.txt		# already solved
	./maximal -KRx waves/squeegee/squee010.txt		# already solved
	./maximal -KRx waves/squeegee/squee018.txt		# solved-50 symmetric condition for n position as the m position of solved-49; 7300 lines
	./maximal -KRx waves/squeegee/squee015.txt		# solved-50 symmetric condition for n position as the m position of solved-49; 7300 lines
	./maximal -KRx waves/squeegee/squee021.txt		# already solved
	./maximal -KRx waves/squeegee/squee022.txt		# already solved
	./maximal -KRx waves/squeegee/squee023.txt		# already solved
	./maximal -KRx waves/squeegee/squee025.txt		# already solved
	./maximal -KRx waves/squeegee/squee026.txt		# already solved
	./maximal -KRx waves/squeegee/squee027.txt		# already solved
	./maximal -KRx waves/squeegee/squee028.txt		# already solved
	./maximal -KRx waves/squeegee/squee029.txt		# already solved
	./maximal -KRx waves/squeegee/squee030.txt		# already solved

echo
echo
echo
echo "$0"
echo
echo
./surfboard-checkmha
echo 'Commit WCR average of 34 (PISO=6): 0.486765 (chowder-free)' | tee -a Corduroy.log
echo 'Commit WCR average of 34 (PISO=5): 0.485882 (chowder-free)' | tee -a Corduroy.log
echo 'Commit WCR average of 34 (PISO=4): 0.475588 (chowder-free)' | tee -a Corduroy.log
echo 'Commit WCR average of 34 (PISO=3): 0.458235 (chowder-free)' | tee -a Corduroy.log
echo | tee -a Corduroy.log
