#!/bin/bash
echo >> Corduroy.log
echo '                                               < fractal_splitting >' >> Corduroy.log

while getopts c option
do
case "${option}"
in
c) 	echo 'with fresh compile (-c)' >> Corduroy.log
	./surfboard-Pop_Up
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
        rm Surf_wavereport.mha
fi


# DIAGNOSTIC TESTS START ON LINE 21
./maximal -D 8 -aKR  waves/chowder/seq26-snippet.txt 
./maximal -D 8 -aKR  waves/chowder/gal11-knot1.txt 
./maximal -D 8 -aKR  waves/chowder/seq26-variations1.txt 
./maximal -D 8 -aKR  waves/chowder/seq26-variations2.txt 
./maximal -D 8 -aKR  waves/chowder/snippet-string02-t.txt
./maximal -D 8 -aKR  waves/chowder/snippet-seq-014-cycle3.txt 

./surfboard-checkmha
echo 'Previous commit WCR average of 6 allowing all k-mers in cinch-k: 0.372   ' | tee -a Corduroy.log
echo 'Previous commit WCR average of 6 allowing only k = 1 in cinch-k: 0.407333' | tee -a Corduroy.log

echo | tee -a Corduroy.log
