#!/bin/bash
#

echo '                                               < ragdoll washing machine >' >> Corduroy.log

if [ -f Surf_wavereport.mha ]; then
        rm Surf_wavereport.mha
fi
if [ -f waves/foam_and_chowder.mha ]; then
        rm waves/foam_and_chowder.mha
fi

./surfboard-Pop_up

for i in {1..10000}
do
	echo "                                                                                                                                                $i"
	./maximal -Rn  -X 2 -S $i waves/experimental/pattern-1a-20pc_GC.txt
    ./maximal -Rn  -X 2 -S $i waves/experimental/pattern-1b-80pc_GC.txt
    ./maximal -Rn  -X 2 -S $i waves/experimental/pattern-2a-50pc_GC.txt
    ./maximal -Rn  -X 2 -S $i waves/experimental/pattern-2b-50pc_GC.txt
    ./maximal -Rn  -X 2 -S $i waves/experimental/pattern-3a-60pc_GC.txt
done

echo
echo
echo
echo "$0"
echo
echo
./surfboard-checkmha

