#!/bin/bash
echo >> Corduroy.log
echo '                                               < squid: b 3 -x trial 4 chowder >' >> Corduroy.log

while getopts c option
do
case "${option}"
in
c) 	./surfboard-Pop_Up
	grep 'define b' src/microhom-skor.h | tee -a Corduroy.log
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
	    rm Surf_wavereport.mha
fi

	# cinch-t originating 2-D conflict

	# cinch-k originating 2-D conflict

	# solved: push new solved runs onto top of stack starting w/ solved-55 coordinated with active squeegee solving
	./maximal -KnxR waves/squeegee/squid~44.txt	# solved-62 delete cyc_o condition w/in cyclelize_tela; P3-only
	./maximal -KnxR waves/squeegee/squid~46.txt	# solved-61 delete block in cinch_k; # P3/4/5/6
	./maximal -KnxR waves/squeegee/squid~20.txt	# solved-61 delete block in cinch_k; # P3/4
	./maximal -KnxR waves/squeegee/squid~42.txt	# solved-60 see below; P3/4/5/6 --> P3/P4-only w/ solved-58
	./maximal -KnxR waves/squeegee/squid~14.txt	# solved-60 see below; P3/4
	./maximal -KnxR waves/squeegee/squid~02.txt	# solved-60 cinch-k k=1 avoiding paralogy columns, complexity function
	./maximal -KnxR waves/squeegee/squid~06.txt	# solved-60 cinch-k k=1 avoiding paralogy columns, complexity function
	./maximal -KnxR waves/squeegee/squid~12.txt	# solved-60 cinch-k k=1 avoiding paralogy columns, complexity function
	./maximal -KnxR waves/squeegee/squid~16.txt	# solved-60 cinch-k k=1 avoiding paralogy columns, complexity function
	./maximal -KnxR waves/squeegee/squid~18.txt	# solved-60 cinch-k k=1 avoiding paralogy columns, complexity function
	./maximal -KnxR waves/squeegee/squid~26.txt	# solved-60 cinch-k k=1 avoiding paralogy columns, complexity function
	./maximal -KnxR waves/squeegee/squid~28.txt	# solved-60 cinch-k k=1 avoiding paralogy columns, complexity function
	./maximal -KnxR waves/squeegee/squid~30.txt	# solved-60 cinch-k k=1 avoiding paralogy columns, complexity function
	./maximal -KnxR waves/squeegee/squid~32.txt	# solved-60 cinch-k k=1 avoiding paralogy columns, complexity function
	./maximal -KnxR waves/squeegee/squid~48.txt	# solved-60 cinch-k k=1 avoiding paralogy columns, complexity function
	./maximal -KnxR waves/squeegee/squid~38.txt	# solved-59 another sub-in for isfractal(); 7397 lines <--prev. solved by max-04 max-05; P3-only
	./maximal -KnxR waves/squeegee/squid~10.txt	# solved-59 another sub-in for isfractal(); 7397 lines
	./maximal -KnxR waves/squeegee/squid~08.txt	# solved-58 new isfractal(); squid~08 P3-only chow w/ <1000 REC; 7387 lines
	./maximal -KnxR waves/squeegee/squid~36.txt	# P3/4/5/6; w/ solved-58
	./maximal -KnxR waves/squeegee/squid~40.txt	# w/ solved-58
	./maximal -KnxR waves/squeegee/squid~04.txt	# w/ solved-58
	./maximal -KnxR waves/snippets/snippet-P6-chow-01.txt	# solved-57, cinch_k module; 7346 lines
	./maximal -KnxR waves/squeegee/squid~22.txt	# solved-57, cinch_k_module; 7346 lines; previously solved by max-04; P3/4/5/6
	./maximal -KnxR waves/squeegee/squid~34.txt	# solved-56; mark_tela code for partially fractal cycling isl.; recently chowder P3/4/5/6; 7345 lines
	./maximal -KnxR waves/squeegee/squid~24.txt	# solved-55 7319 lines; previously solved by max-04 and max-05; mark_tela adjust

echo
echo
echo
echo "$0"
echo
echo
./surfboard-checkmha
echo 'Commit WCR average of 25 (b=6): 0.517  (chowder-free)' | tee -a Corduroy.log
echo 'Commit WCR average of 25 (b=5): 0.5098 (chowder-free)' | tee -a Corduroy.log
echo 'Commit WCR average of 25 (b=4): 0.5102 (chowder-free)' | tee -a Corduroy.log
echo 'Commit WCR average of 25 (b=3): 0.4782 (chowder-free)' | tee -a Corduroy.log
echo | tee -a Corduroy.log
