#!/bin/bash
echo >> Corduroy.log
echo '                                               < eat nuggets >' >> Corduroy.log

while getopts c option
do
case "${option}"
in
c) 	./surfboard-Pop_Up
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
	    rm Surf_wavereport.mha
fi

	# conflict begins in cinch-t

	# conflict begins in cinch-k

	# solved
	./maximal -KR waves/chowder/nugget-42356.txt	# solved-13	
	./maximal -KR waves/chowder/nugget-47633.txt	# solved-14 cinch-k x_history propagation
	./maximal -KR waves/chowder/nugget-50546.txt	# solved-14 cinch-k x_history propagation
	./maximal -KR waves/chowder/nugget-00002.txt	# solved-15 delete unnecessary cinch-k block blocking needed cinch
	./maximal -KR waves/chowder/nugget-00001.txt	# solved-16 less strict entry into split fractal block in mark_tela
	./maximal -KR waves/chowder/nugget-00003.txt	# solved-16 less strict entry into split fractal block in mark_tela
	./maximal -KR waves/chowder/nugget-00004.txt	# solved-16 less strict entry into split fractal block in mark_tela
	./maximal -KR waves/chowder/nugget-00006.txt	# solved-17 new skip condition in mark_tela; simplified check in cinch_k
	./maximal -KR waves/chowder/nugget-00005.txt	# solved-18 adjustment to next_k() w.r.t. imperfect TRs
	./maximal -KR waves/chowder/nugget-00007.txt	# solved-19 new mark_tela() module to skip 1st of cycling isle if overlapping upstream parent w/ fractals
	./maximal -KR waves/chowder/nugget-00008.txt	# solved-20 strand symmetric module to new mark_tela() module of solved-19/previous nugget

echo
echo
echo
echo "$0"
echo
echo
./surfboard-checkmha
echo 'Commit WCR average of 11 (PISO=6|5|4|3): 0.450 (chowder-free)' | tee -a Corduroy.log
echo | tee -a Corduroy.log
