#!/bin/bash

if [ -f Surf_wavereport.mha ]; then
        rm Surf_wavereport.mha
fi

for i in {1..2500}
do
	./maximal -Rn -X 2 waves/seals/vnd_ex3_Dmela.txt
	./maximal -Rn -X 2 waves/seals/vnd_ex3_Dsimu.txt
	./maximal -Rn -X 2 waves/seals/vnd_ex3_Derec.txt
	./maximal -Rn -X 2 waves/seals/vnd_ex3_Dyaku.txt
	./maximal -Rn -X 2 waves/seals/vnd_ex3_Dbiar.txt
	./maximal -Rn -X 2 waves/seals/vnd_ex3_Dsuzu.txt
	./maximal -Rn -X 2 waves/seals/vnd_ex3_Danan.txt
	./maximal -Rn -X 2 waves/seals/vnd_ex3_Dbipe.txt
	./maximal -Rn -X 2 waves/sharks/vnd_NEE_Dmela.txt
	./maximal -Rn -X 2 waves/sharks/vnd_NEE_Dsimu.txt
	./maximal -Rn -X 2 waves/sharks/vnd_NEE_Derec.txt
	./maximal -Rn -X 2 waves/sharks/vnd_NEE_Dyaku.txt
	./maximal -Rn -X 2 waves/sharks/vnd_NEE_Dbiar.txt
	./maximal -Rn -X 2 waves/sharks/vnd_NEE_Dsuzu.txt
	./maximal -Rn -X 2 waves/sharks/nab_DWME_Dmela.txt
done

./surfboard-checkmha

grep -c ex3_Dmela Surf_wavereport.log
grep -c ex3_Dsimu Surf_wavereport.log
grep -c ex3_Derec Surf_wavereport.log
grep -c ex3_Dyaku Surf_wavereport.log
grep -c ex3_Dbiar Surf_wavereport.log
grep -c ex3_Dsuzu Surf_wavereport.log
grep -c ex3_Danan Surf_wavereport.log
grep -c ex3_Dbipe Surf_wavereport.log
grep -c NEE_Dbiar Surf_wavereport.log
grep -c NEE_Derec Surf_wavereport.log
grep -c NEE_Dmela Surf_wavereport.log
grep -c NEE_Dsimu Surf_wavereport.log
grep -c NEE_Dsuzu Surf_wavereport.log
grep -c NEE_Dyaku Surf_wavereport.log
grep -c WME_Dmela Surf_wavereport.log

