#!/bin/bash
echo >> Corduroy.log
echo '                                               < churly churly >' >> Corduroy.log

while getopts c option
do
case "${option}"
in
c) 	./surfboard-Pop_Up
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
	    rm Surf_wavereport.mha
fi

	# conflict begins in cinch-t

	# conflict begins in cinch-k

	# solved
	./maximal -KR waves/chowder/churly-01.txt	# solved-21 delete clear_mem module in mark_tela 
	./maximal -KR waves/chowder/churly-02.txt	# solved-21 delete clear_mem module in mark_tela 
	./maximal -KR waves/chowder/churly-03.txt	# solved-21 delete clear_mem module in mark_tela 
	./maximal -KR waves/chowder/churly-04.txt	# solved-21 delete clear_mem module in mark_tela 
	./maximal -KR waves/chowder/churly-06.txt	# solved-21 delete clear_mem module in mark_tela 
	./maximal -KR waves/chowder/churly-07.txt	# solved-21 delete clear_mem module in mark_tela 
	./maximal -KR waves/chowder/churly-05.txt	# solved-22 adjustment to cyclelize_tela()
	./maximal -KR waves/chowder/churly-09.txt	# solved-22 adjustment to cyclelize_tela()
	./maximal -KR waves/chowder/churly-08.txt	# solved-23 new cinch-k low-complexity block
	./maximal -KR waves/chowder/churly-10.txt	# solved-24 adjustment to new low-complexity block in cinch-k
													# solved-25--26 -> b4 script (deprecated script)
	./maximal -KR waves/chowder/churly-11.txt	# solved-27 new cinch-k cluster-f*ck block
	./maximal -KR waves/chowder/churly-12.txt	# solved-28 slight adjustment to new cinch-k block of solved-27
	./maximal -KR waves/chowder/churly-13.txt	# solved-28 slight adjustment to new cinch-k block of solved-27
	./maximal -KR waves/chowder/churly-14.txt	# solved-29 new mark_tela() block for conflict marking
	./maximal -KR waves/chowder/churly-15.txt	# solved-29 new mark_tela() block for conflict marking
	./maximal -KR waves/chowder/churly-16.txt	# solved-30 adjustment for new cinch-k block of solved 27-28
	./maximal -KR waves/chowder/churly-17.txt	# solved-31 trivial lenseq boundary condition in cinch-t & mark_tela, > not >=
	./maximal -KR waves/chowder/churly-18.txt	# solved-32 push_mem 13/14 edits and deletions in mark_tela
	./maximal -KR waves/chowder/churly-19.txt	# solved-32 push_mem 13/14 edits and deletions in mark_tela 
	./maximal -KR waves/chowder/churly-20.txt	# solved-33 push_mem 13/14 continued w/ an add'l exclusion for push_mem 8 fractals
	./maximal -KR waves/chowder/churly-21.txt	# solved-33 push_mem 13/14 continued w/ an add'l exclusion for push_mem 8 fractals 
	./maximal -KR waves/chowder/churly-22.txt	# solved-34 simplification to cyclelize_tela(); related to solved-22 edits
	./maximal -KR waves/chowder/churly-23.txt	# solved-35 cinch-k module based on tela struct logic
	./maximal -KR waves/chowder/churly-24.txt	# solved-35 cinch-k module based on tela struct logic 
	./maximal -KR waves/chowder/churly-25.txt	# solved-36 cinch-k tela struct logic continued
	./maximal -KR waves/chowder/churly-26.txt	# solved-37 correction to recent cinch-k lines wrt location of parent in tela
	./maximal -KR waves/chowder/churly-27.txt	# solved-37 correction to recent cinch-k lines wrt location of parent in tela 
	./maximal -KR waves/chowder/churly-29.txt	# solved-37 correction to recent cinch-k lines wrt location of parent in tela 
	./maximal -KR waves/chowder/churly-30.txt	# solved-37 correction to recent cinch-k lines wrt location of parent in tela 
	./maximal -KR waves/chowder/churly-31.txt	# solved-37 correction to recent cinch-k lines wrt location of parent in tela 
	./maximal -KR waves/chowder/churly-32.txt	# solved-37 correction to recent cinch-k lines wrt location of parent in tela 
	./maximal -KR waves/chowder/churly-33.txt	# solved-37 correction to recent cinch-k lines wrt location of parent in tela 
	./maximal -KR waves/chowder/churly-34.txt	# solved-37 correction to recent cinch-k lines wrt location of parent in tela 
	./maximal -KR waves/chowder/churly-35.txt	# solved-37 correction to recent cinch-k lines wrt location of parent in tela 
	./maximal -KR waves/chowder/churly-36.txt	# solved-37 correction to recent cinch-k lines wrt location of parent in tela 
	./maximal -KR waves/chowder/churly-28.txt	# solved-38 new cinch-k module underlying conflict in fractal TR
	./maximal -KR waves/chowder/churly-37.txt	# solved-39 adding a check stat2 for fract (time to consolidate fract rows...)
	./maximal -KR waves/chowder/churly-38.txt	# solved-40 lines to convert prev. quasi "Fract" to true "fract" by checking k2

echo
echo
echo
echo "$0"
echo
echo
./surfboard-checkmha
echo 'Commit WCR average of 38 (b=6): 0.504474 (chowder-free)' | tee -a Corduroy.log
echo 'Commit WCR average of 38 (b=5): 0.496579 (chowder-free)' | tee -a Corduroy.log
echo 'Commit WCR average of 38 (b=4): 0.485    (chowder-free)' | tee -a Corduroy.log
echo 'Commit WCR average of 38 (b=3): 0.461842 (chowder-free)' | tee -a Corduroy.log
echo | tee -a Corduroy.log
