#!/bin/bash
#

echo '                                               < ragdoll washing machine >' >> Corduroy.log

if [ ! -f maximal ]; then
	./surfboard-Pop_Up
fi
if [ -f Surf_wavereport.mha ]; then
        rm Surf_wavereport.mha
fi
if [ -f waves/foam_and_chowder.mha ]; then
        rm waves/foam_and_chowder.mha
fi

for i in {1..20000}
do
	echo "                                                                                                                                                $i"
	./maximal -Rnx -X2 -S$i waves/experimental/pattern-1a-20pc_GC.txt
	./maximal -Rnx -X2 -S$i waves/experimental/pattern-1b-80pc_GC.txt
	./maximal -Rnx -X2 -S$i waves/experimental/pattern-3a-60pc_GC.txt
	./maximal -Rnx -X2 -S$i waves/experimental/pattern-2a-50pc_GC.txt
	./maximal -Rnx -X2 -S$i waves/experimental/pattern-2b-50pc_GC.txt
	./maximal -Rnx -X2 -S$i waves/experimental/pattern-3b-60pc_GC.txt
	./maximal -Rnx -X2 -S$i -Y80 waves/experimental/pattern-5a-92pc_Y.txt 
done

echo
echo
echo
echo "$0"
echo
echo
./surfboard-checkmha

