#!/bin/bash
for i in {1..2500}
do
	./maximal -RnXX waves/Danan_ex3.txt
	./maximal -RnXX waves/Dbipe_ex3.txt
	./maximal -RnXX waves/Dbiar_ex3.txt
	./maximal -RnXX waves/Derec_ex3.txt
	./maximal -RnXX waves/Dmela_ex3.txt
	./maximal -RnXX waves/Dsimu_ex3.txt
	./maximal -RnXX waves/Dsuzu_ex3.txt
	./maximal -RnXX waves/Dyaku_ex3.txt
	./maximal -RnXX waves/Dbiar_NEE.txt
	./maximal -RnXX waves/Derec_NEE.txt
	./maximal -RnXX waves/Dmela_NEE.txt
	./maximal -RnXX waves/Dsimu_NEE.txt
	./maximal -RnXX waves/Dsuzu_NEE.txt
	./maximal -RnXX waves/Dyaku_NEE.txt
	./maximal -RnXX waves/Dmela_DWME.txt
done

./surfboard-checkmha

grep -c Danan_ex3 surf_wavereport.log
grep -c Dbipe_ex3 surf_wavereport.log
grep -c Dbiar_ex3 surf_wavereport.log
grep -c Derec_ex3 surf_wavereport.log
grep -c Dmela_ex3 surf_wavereport.log
grep -c Dsimu_ex3 surf_wavereport.log
grep -c Dsuzu_ex3 surf_wavereport.log
grep -c Dyaku_ex3 surf_wavereport.log
grep -c Dbiar_NEE surf_wavereport.log
grep -c Derec_NEE surf_wavereport.log
grep -c Dmela_NEE surf_wavereport.log
grep -c Dsimu_NEE surf_wavereport.log
grep -c Dsuzu_NEE surf_wavereport.log
grep -c Dyaku_NEE surf_wavereport.log
grep -c Dmela_DWME surf_wavereport.log

