#!/bin/bash
echo >> Corduroy.log
echo '                                               < squirt chowder >' >> Corduroy.log

while getopts c option
do
case "${option}"
in
c) 	./surfboard-Pop_Up
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
	    rm Surf_wavereport.mha
fi

	# cinch-t originating 2-D conflict
	./maximal -KnxR -D 8 waves/squeegee/squirt_11-b6.txt		# chowder with both v4.34-lcl-09 and v4.35

	# cinch-k originating 2-D conflict
	./maximal -KnxR -D 8 waves/squeegee/squirt_10-b6.txt		# non-chowder with v4.34-lcl-09

	# solved: push new solved runs onto top of stack starting w/ solved-64 
	./maximal -KnxR waves/squeegee/squirt_09-b6.txt		# solved-72 mark_tela() edits; b3--6
	./maximal -KnxR waves/squeegee/squirt_08-b6.txt		# solved-71 hack mark_tela() edit w/ MAGIC # k-mer size condition; b3--6
	./maximal -KnxR waves/squeegee/squirt_07-b6.txt		# solved-70 muting deprecated code in mark_tela(); b3--6
	./maximal -KnxR waves/squeegee/squirt_06-b6.txt		# solved-69 sub-threshold fractals condition to skip if next parent column is perfect k; b3--6
	./maximal -KnxR waves/squeegee/squirt_05-b6.txt		# solved-68 mark_tela edits continued again; b4--6
	./maximal -KnxR waves/squeegee/squirt_04-b6.txt		# solved-67 mark_tela edits continued; b3--6
	./maximal -KnxR waves/squeegee/squirt_03-b6.txt		# solved-66 mark_tela edits; b4-6
	./maximal -KnxR waves/squeegee/squirt_02-b6.txt		# solved-65 delete all_S condition in split fractals module of mark_tela(); b3-6
	./maximal -KnxR waves/squeegee/squirt_01-b6.txt		# solved-64 new module in mark_tela concerning cycling islands w/ perfect and imperfect columns b3-6

echo
echo
echo
echo "$0"
echo
echo
./surfboard-checkmha
echo 'Commit WCR average of 9 (b=6): 0.513333 (9 / 9 solved)' | tee -a Corduroy.log
echo 'Commit WCR average of 9 (b=6): 0.521111 (9 / 9 solved)' | tee -a Corduroy.log
echo 'Commit WCR average of 9 (b=4): 0.511111 (9 / 9 solved)' | tee -a Corduroy.log
echo 'Commit WCR average of 9 (b=3): 0.486667 (9 / 9 solved)' | tee -a Corduroy.log
echo | tee -a Corduroy.log
