#!/bin/bash

if [ -f Corduroy.log ]; then
        mv Corduroy.log local_tmp/
fi

answer="n"

./surfboard-Pop_Up
sed -n '92s/\(opt_b = \){0, \(.\).*/Transition matching threshold k-size: \1\2/p' src/microhomology.h 
echo
echo | tee -a Corduroy.log
echo "$0: Hit <enter> to start cleanup_set-all. Or hit 'q' to quit script entirely."
read -s -n1 answer

if [ "$answer" == "q" ] || [ "$answer" == "Q" ]; then
    exit 1
else
	./surfboard-cleanup_set-all 

	echo "$0: Hit <enter> to start cleanup_set-eatchowder."
	read -s -n1 answer
	./surfboard-cleanup_set-eatchowder 

	echo "$0: Hit <enter> to start cleanup_set-eatchowdah."
	read -s -n1 answer
	./surfboard-cleanup_set-eatchowdah

	echo "$0: Hit <enter> to start cleanup_set-eatnuggets."
	read -s -n1 answer
	./surfboard-cleanup_set-eatnuggets

	echo "$0: Hit <enter> to start cleanup_set-fractal_splits."
	read -s -n1 answer
	./surfboard-cleanup_set-fractal_splits 

	echo "$0: Hit <enter> to start cleanup_set-sand_dunes."
	read -s -n1 answer
	./surfboard-cleanup_set-sand_dunes 

	echo "$0: Hit <enter> to start cleanup_set-churlychurly."
	read -s -n1 answer
	./surfboard-cleanup_set-churlychurly 

	echo "$0: Hit <enter> to start cleanup_set-squid."
	read -s -n1 answer
	./surfboard-cleanup_set-squid

	echo "$0: Hit <enter> to start cleanup_set-squeegee."
	read -s -n1 answer
	./surfboard-cleanup_set-squeegee

	echo "$0: Hit <enter> to start cleanup_set-squirt."
	read -s -n1 answer
	./surfboard-cleanup_set-squirt

	echo "$0: Hit <enter> to start cleanup_set-squint."
	read -s -n1 answer
	./surfboard-cleanup_set-squint
fi

