#!/bin/bash

echo 'sand dunes' >> corduroy.log

while getopts c option
do
case "${option}"
in
c) 	echo 'with fresh compile (-c)' >> corduroy.log
	./surfboard-Pop_Up
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
        rm Surf_wavereport.mha
fi

# CHOWDER TESTS 
./maximal -DKnxrL waves/chowder/seq-64-snippet-Rnx_symmetry.txt 
./maximal -DKnxrL waves/chowder/seq-64-snippet-Rnx_symmetry.txt -C

