#!/bin/bash
if [ -f Surf_wavereport.mha ]; then
        rm Surf_wavereport.mha
fi
	./maximal -Rn waves/Danan_ex3.txt
	./maximal -Rn waves/Dbipe_ex3.txt
	./maximal -Rn waves/Dbiar_ex3.txt
	./maximal -Rn waves/Derec_ex3.txt
	./maximal -Rn waves/Dmela_ex3.txt
	./maximal -Rn waves/Dsimu_ex3.txt
	./maximal -Rn waves/Dsuzu_ex3.txt
	./maximal -Rn waves/Dyaku_ex3.txt
	./maximal -Rn waves/Dbiar_NEE.txt
	./maximal -Rn waves/Derec_NEE.txt
	./maximal -Rn waves/Dmela_NEE.txt
	./maximal -Rn waves/Dsimu_NEE.txt
	./maximal -Rn waves/Dsuzu_NEE.txt
	./maximal -Rn waves/Dyaku_NEE.txt
	./maximal -Rn waves/Dmela_DWME.txt

./surfboard-checkmha
