#!/bin/bash
echo >> Corduroy.log
echo '                                               < eat chowder >' >> Corduroy.log

answer="n"

while getopts c option
do
case "${option}"
in
c) 	./surfboard-Pop_Up
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
	    rm Surf_wavereport.mha
fi

# Solved but leaving here to keep track of their status:
# tput bel
# echo
# echo "$0: Hit <enter> to run recently solved chowder runs. Or, enter 'q' to quit script entirely."
# read -s -n1 answer
# if [ "$answer" == "q" ] || [ "$answer" == "Q" ]; then
# 	exit 1
# else
	./maximal -KR waves/chowder/flotsam_06F.txt							# solved in the script commenting before-time
	./maximal -KR waves/chowder/flotsam_09F.txt							# solved in the script commenting before-time
	./maximal -KR waves/chowder/flotsam_15F.txt							# solved in the script commenting before-time
	./maximal -KR waves/chowder/flotsam_16F.txt							# solved in the script commenting before-time
	./maximal -KR waves/chowder/flotsam_22R.txt							# solved in the script commenting before-time
	./maximal -KR waves/chowder/flotsam_26R.txt							# solved in the script commenting before-time
	./maximal -KR waves/chowder/flotsam_27R.txt							# solved in the script commenting before-time
	./maximal -KR waves/chowder/flotsam_32R.txt							# solved in the script commenting before-time
	./maximal -KR waves/chowder/flotsam_33F.txt							# solved in the script commenting before-time
	./maximal -KR waves/chowder/flotsam_38F.txt							# solved in the script commenting before-time
	./maximal -KR waves/chowder/jetsam-05-Dana_vnd_ex3_FY-100mer.txt 	# solved in the script commenting before-time
	./maximal -KR waves/chowder/snippet-jetsam-05.txt					# solved in the script commenting before-time
	./maximal -KR waves/chowder/flotsam_03F.txt 						# solved in the script commenting before-time
	./maximal -KR waves/chowder/flotsam_08F.txt 						# solved in the script commenting before-time
	./maximal -KR waves/chowder/flotsam_17F.txt 						# solved in the script commenting before-time
	./maximal -KR waves/chowder/flotsam_20R.txt 						# solved in the script commenting before-time
	./maximal -KR waves/chowder/flotsam_37F.txt 						# solved in the script commenting before-time
	./maximal -KR waves/chowder/jetsam-04-Dsuz_vnd_NEE_FY-100mer.txt 	# solved-1
	./maximal -KR waves/chowder/flotsam_42F.txt							# solved-2
	./maximal -KR waves/chowder/flotsam_47R.txt							# solved-2
	./maximal -KR waves/chowder/flotsam_24R.txt							# solved-3 
	./maximal -KR waves/chowder/flotsam_30R.txt 						# solved-3
	./maximal -KR waves/chowder/flotsam_02F.txt		# solved-4 new cinch-k block to match non-fractal knot spanning overlapping TRs above txt below
	./maximal -KR waves/chowder/flotsam_11F.txt		# solved-4 new cinch-k block to match non-fractal knot spanning overlapping TRs above txt below
	./maximal -KR waves/chowder/flotsam_13F.txt		# solved-4 new cinch-k block to match non-fractal knot spanning overlapping TRs above txt below
	./maximal -KR waves/chowder/flotsam_18F.txt		# solved-4 new cinch-k block to match non-fractal knot spanning overlapping TRs above txt below
	./maximal -KR waves/chowder/flotsam_19F.txt		# solved-4 new cinch-k block to match non-fractal knot spanning overlapping TRs above txt below
	./maximal -KR waves/chowder/flotsam_34R.txt		# solved-4 new cinch-k block to match non-fractal knot spanning overlapping TRs above txt below
	./maximal -KR waves/chowder/flotsam_39F.txt		# solved-4 new cinch-k block to match non-fractal knot spanning overlapping TRs above txt below
	./maximal -KR waves/chowder/s08-k.txt			# solved-4 new cinch-k block to match non-fractal knot spanning overlapping TRs above txt below
	./maximal -KR waves/chowder/s18-k.txt			# solved-4 new cinch-k block to match non-fractal knot spanning overlapping TRs above txt below
	./maximal -KR waves/chowder/s34-k.txt			# solved-4 new cinch-k block to match non-fractal knot spanning overlapping TRs above txt below
	./maximal -KR waves/chowder/st04-k.txt			# solved-4 new cinch-k block to match non-fractal knot spanning overlapping TRs above txt below
	./maximal -KR waves/chowder/st06-k.txt			# solved-4 new cinch-k block to match non-fractal knot spanning overlapping TRs above txt below
	./maximal -KR waves/chowder/flotsam_04F.txt		# solved-5 generalization of #4
	./maximal -KR waves/chowder/flotsam_05F.txt		# solved-5 generalization of #4
	./maximal -KR waves/chowder/flotsam_07F.txt		# solved-5 generalization of #4
	./maximal -KR waves/chowder/st02-k.txt			# solved-5 generalization of #4
	./maximal -KR waves/chowder/flotsam_43R.txt		# solved-6 generalization of #4, loosening condition 2
	./maximal -KR waves/chowder/s20-k.txt			# solved-7 generalization oy #4, loosening condition 1
	./maximal -KR waves/chowder/s22-k.txt			# solved-7 generalization oy #4, loosening condition 1
	./maximal -KR waves/chowder/s24-k.txt			# solved-7 generalization oy #4, loosening condition 1
	./maximal -KR waves/chowder/flotsam_01F.txt 	# solved-8 explicit test of fractality in mark_tela block invoking get_k2
	./maximal -KR waves/chowder/flotsam_23R.txt 	# solved-9 new split fractal variety, cinch-t type; mark_tela fix
	./maximal -KR waves/chowder/s30-t.txt		 	# solved-9 new split fractal variety, cinch-t type; mark_tela fix
	./maximal -KR waves/chowder/string02-t.txt 		# solved-10 after code review of split fractal cases in mark_tela
	./maximal -KR waves/chowder/flotsam_10F.txt		# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/flotsam_14F.txt		# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/flotsam_21R.txt		# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/flotsam_28F.txt		# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/flotsam_31R.txt		# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/flotsam_35R.txt		# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/flotsam_36R.txt		# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/flotsam_40R.txt		# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/flotsam_41R.txt		# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/flotsam_44R.txt		# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/flotsam_45F.txt		# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/flotsam_46R.txt		# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/s06-k.txt			# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/s10-k.txt			# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/s14-k.txt			# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/s26-k.txt			# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/s28-k.txt			# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/s36-k.txt			# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/s38-k.txt			# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/s46-k.txt			# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/s48-k.txt			# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/s50-k.txt			# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/st08-k.txt			# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/st10-k.txt			# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/str02-k.txt			# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/str04-k.txt			# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/stri02-k.txt		# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/stri08-k.txt		# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/stri10-k.txt		# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/stri12-k.txt		# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/strin02-k.txt 		# solved-11 multi-line partially-fractal TR at nexus of overlapping TRs
	./maximal -KR waves/chowder/s32-k.txt			# solved-12 multi-line conflict at nexus of overlapping TRs
	./maximal -KR waves/chowder/s42-k.txt			# solved-12 multi-line conflict at nexus of overlapping TRs
	./maximal -KR waves/chowder/str06-k.txt			# solved-12 multi-line conflict at nexus of overlapping TRs
	./maximal -KR waves/chowder/stri04-k.txt		# solved-12 multi-line conflict at nexus of overlapping TRs
	./maximal -KR waves/chowder/s40-k.txt			# solved-13 cinch-k mini-block
# fi

echo
echo
echo
echo "$0"
echo
echo
./surfboard-checkmha
echo 'Current commit WCR average of 82, allowing all k-mers in cinch-k: 0.467768' | tee -a Corduroy.log
echo | tee -a Corduroy.log
