#!/bin/bash

echo 'Surf wave report summary: '
echo '._                                                                                                                            '
echo '\\\_M                                                                                                                         '
echo '\\\\\_H                                                                                            \v/                        '
echo '\\\\\\\_A_________.~~.o.~"~._.~`"~._.~"~._.~"~._.~"~._.~`"~._.~"~._.~"~._^_.~"~._.~"~._.~"~._.~`"~.-0-.~"~._.~"~._.~"~._.~"~._'
echo '```````^:^````````                                                                                 /|\                        '
echo 'Number of tests initiated:'
grep -c waves Surf_wavereport.log
echo
echo 'Number of tests completed:'
grep -cE '^v' Surf_wavereport.log
echo
echo 'Number of tests with PASS 1000:'
grep -cE '\t1000' Surf_wavereport.log 
echo
echo 'Number of tests with perfect 1-D recovery (REC:1000):'
grep -cE 'C.1000' Surf_wavereport.log 
echo
echo 'Number of tests using nudging'
grep -cE -v 'NDG: 0' Surf_wavereport.log 
echo
echo 'Number of tests with checktransits:'
grep -cE 'checktransit' Surf_wavereport.log 
echo
awk -F'[\t]' '{sum+=$5} END {print "WCR AVERAGE: " sum/NR}' Surf_wavereport.log 
echo
echo 'First and last runs:'
head -n 1 Surf_wavereport.log
tail -n 1 Surf_wavereport.log
echo
echo 'Tests with PASS < 1000:'
grep ^v Surf_wavereport.log | grep -vE '\t1000' 
echo 'Tests with REC < 1000:'
grep ^v Surf_wavereport.log | grep -vE 'REC:1000' 
echo 'Tests canceled (shown with preceding runs for context):'
grep -B1 Canceled Surf_wavereport.log | sed '/^--$/d'
echo
echo 'Line counts:'
wc -l src/*.c src/*.h
echo

