#!/bin/bash

echo '                                               < ragdoll washing machine >' >> Corduroy.log
echo
echo 'System:'               >> Corduroy.log
uname -rmps                  >> Corduroy.log
echo 'Codebase line counts:' >> Corduroy.log
wc -l src/*.c src/*.h        >> Corduroy.log
echo                         >> Corduroy.log

while getopts c option
do
case "${option}"
in
c)      ./surfboard-Pop_Up
        sleep 2 # TO GIVE CHANCE TO SEE IF ANY COMPILE WARNINGS
        ;;
esac
done

if [ ! -f lineup ]; then
	./surfboard-Pop_Up
fi
if [ -f Surf_wavereport.mha ]; then
        rm Surf_wavereport.mha
fi
if [ -f waves/foam_and_chowder.mha ]; then
        rm waves/foam_and_chowder.mha
fi

for i in {1..20000}  # to 20000 historically, for 140 k total tests
do
	echo "                                                                                                                                                $i"
	./lineup -Rnx -X2 -S$i waves/experimental/pattern-1a-20pc_GC.txt
	./lineup -Rnx -X2 -S$i waves/experimental/pattern-1b-80pc_GC.txt
	./lineup -Rnx -X2 -S$i waves/experimental/pattern-3a-60pc_GC.txt
	./lineup -Rnx -X2 -S$i waves/experimental/pattern-2a-50pc_GC.txt
	./lineup -Rnx -X2 -S$i waves/experimental/pattern-2b-50pc_GC.txt
	./lineup -Rnx -X2 -S$i waves/experimental/pattern-3b-60pc_GC.txt
	./lineup -Rnx -X2 -S$i -Y80 waves/experimental/pattern-5a-92pc_Y.txt 
done

echo
echo
echo
echo "$0"
echo
echo
./surfboard-checkmha
echo 'WCR avg history (140k tests @ b=3): ~0.4365--0.4367' | tee -a Corduroy.log
echo | tee -a Corduroy.log
