#!/bin/bash

while getopts c option
do
case "${option}"
in
c) 	./surfboard-Pop_Up
	;;
esac
done

if [ -f Surf_wavereport.mha ]; then
        rm Surf_wavereport.mha
fi


# DIAGNOSTIC TESTS START ON LINE 21
./maximal -DKR waves/chowder/snippet-jetsam-05.txt

./surfboard-checkmha
