#!/bin/bash

while getopts c option
do
case "${option}"
in
c) 	./surfboard-Pop_Up
	;;
esac
done

if [ ! -f maximal ]; then
	./surfboard-Pop_Up
fi
if [ -f Surf_wavereport.mha ]; then
	    rm Surf_wavereport.mha
fi

# -D# 0=default; 1=1D; 2=cinch-t; 3=cinch-l; 4=cinch-k; 5=cinch-d; 6=relax2D; 7= pause at end of run

./maximal -Knx -D7     waves/demo_corpus/demo_01a.txt
./maximal -Knx -D7     waves/demo_corpus/demo_01b.txt
./maximal -Knx -D7     waves/demo_corpus/demo_01c.txt
./maximal -Knx -D7     waves/demo_corpus/demo_01d.txt
./maximal -Knx -D7     waves/demo_corpus/demo_01a.txt -C
./maximal -Knx -D7     waves/demo_corpus/demo_01b.txt -C
./maximal -Knx -D7     waves/demo_corpus/demo_01c.txt -C
./maximal -Knx -D7     waves/demo_corpus/demo_01d.txt -C
./maximal -Knx -D7     waves/demo_corpus/demo_04.txt
./maximal -Knx -D7     waves/demo_corpus/demo_02a.txt
./maximal -Knx -D7     waves/demo_corpus/demo_02b.txt
./maximal -Knx -D7     waves/demo_corpus/demo_02c.txt
./maximal -Knx -D7     waves/demo_corpus/demo_02d.txt
./maximal -Knx -D7     waves/demo_corpus/demo_02e.txt
./maximal -Knx -D7     waves/demo_corpus/demo_02f.txt
./maximal -Knx -D7     waves/demo_corpus/demo_02a.txt
./maximal -Knx -D7     waves/demo_corpus/demo_03b.txt
./maximal -Knx -D7     waves/demo_corpus/demo_03c.txt
./maximal -Knx -D7     waves/demo_corpus/demo_03d.txt
./maximal -Knx -D7     waves/demo_corpus/demo_03e.txt
./maximal -Knx -D7     waves/demo_corpus/demo_03f.txt

