#!/bin/bash
./surfboard-Pop_Up
if [ -f Surf_wavereport.mha ]; then
        rm Surf_wavereport.mha
fi
./maximal -Rna
./maximal -Rnb
./maximal -Rnc
./maximal -Rnd
./maximal -Rne
./maximal -Rnf
./maximal -Rng
./maximal -Rnh
./maximal -Rn waves/seal_vnd_ex3_Dmela.txt
./maximal -Rn waves/seal_vnd_ex3_Dmaur.txt
./maximal -Rn waves/seal_vnd_ex3_Dsech.txt
./maximal -Rn waves/seal_vnd_ex3_Dsimu.txt
./maximal -Rn waves/seal_vnd_ex3_Derec.txt
./maximal -Rn waves/seal_vnd_ex3_Dsant.txt
./maximal -Rn waves/seal_vnd_ex3_Dyaku.txt
./maximal -Rn waves/seal_vnd_ex3_Dbiar.txt
./maximal -Rn waves/seal_vnd_ex3_Dsuzu.txt
./maximal -Rn waves/seal_vnd_ex3_Danan.txt
./maximal -Rn waves/seal_vnd_ex3_Dbipe.txt
./maximal -Rn waves/shark_vnd_NEE_Dmela.txt
./maximal -Rn waves/shark_vnd_NEE_Dmaur.txt
./maximal -Rn waves/shark_vnd_NEE_Dsech.txt
./maximal -Rn waves/shark_vnd_NEE_Dsimu.txt
./maximal -Rn waves/shark_vnd_NEE_Derec.txt
./maximal -Rn waves/shark_vnd_NEE_Dsant.txt
./maximal -Rn waves/shark_vnd_NEE_Dyaku.txt
./maximal -Rn waves/shark_vnd_NEE_Dbiar.txt
./maximal -Rn waves/shark_vnd_NEE_Dsuzu.txt
./maximal -Rn waves/shark_nab_DWME_Dmela.txt
./maximal -Rn waves/tubespit-01-toslip.txt
./maximal -Rn waves/tubespit-02-toslip.txt
./maximal -Rn waves/tubespit-03-tosSt1.txt
./maximal -Rn waves/tubespit-04-tos-ct.txt
./maximal -Rn waves/tubespit-22-tosSt2.txt
./maximal -Rn waves/tubespit-23-tosSt2.txt
./maximal -Rn waves/tubespit-24-tosSt2.txt
./maximal -Rn waves/tubespit-25-tosSt2.txt
./maximal -Rn waves/tubespit-26-tosSt2.txt
./maximal -Rn waves/tubespit-29-toslp2.txt
./maximal -Rn waves/tubespit-30-toslp2.txt
./maximal -Rn waves/tubespit-31-t0edge.txt
./maximal -Rn waves/tubespit-05-koshp1.txt
./maximal -Rn waves/tubespit-06-koslip.txt
./maximal -Rn waves/tubespit-07-koslip.txt
./maximal -Rn waves/tubespit-08-koslp2.txt
./maximal -Rn waves/tubespit-09-koslp3.txt
./maximal -Rn waves/tubespit-18-koshp2.txt
./maximal -Rn waves/tubespit-19-koslp4.txt
./maximal -Rn waves/tubespit-10-cycle1.txt
./maximal -Rn waves/tubespit-11-cycle1.txt
./maximal -Rn waves/tubespit-12-cycle1.txt
./maximal -Rn waves/tubespit-13-cycle2.txt
./maximal -Rn waves/tubespit-14-cycle3.txt
./maximal -Rn waves/tubespit-15-cycle4.txt
./maximal -Rn waves/tubespit-17-cycle5.txt
./maximal -Rn waves/tubespit-16-cyc3_a.txt
./maximal -Rn waves/tubespit-20-cyc3_b.txt
./maximal -Rn waves/tubespit-21-cyc3_c.txt
./maximal -Rn waves/tubespit-27-cycleX.txt
./maximal -Rn waves/tubespit-32-combo1.txt
./maximal -Rn waves/tubespit-28-scrtch.txt
./maximal -Rn waves/tubespit-33-imprf1.txt
./maximal -Rn waves/tubespit-34-imprf2.txt
./maximal -Rn waves/tubespit-35-imprf3.txt
./maximal -Rn waves/tubespit-36-imprf4.txt
./maximal -Rn waves/tubespit-37-imprfk.txt
./maximal -Rn waves/tubespit-38-imprft.txt
./maximal -Rn waves/tubespit-39-imprfk.txt
./maximal -Rn waves/tubespit-40-imprfk.txt
./maximal -Rn waves/tubespit-41-RNAnuc.txt
./maximal -Rn waves/tubespit-41-notRNA.txt
./maximal -Rn waves/tubespit-41-protin.txt
./maximal -Rn waves/tubespit-42-fasta1.txt
./maximal -Rn waves/tubespit-42-fasta2.txt
./maximal -Rn waves/tubespit-43-timprf.txt
./maximal -Rn waves/tubespit-44-tosimp.txt
./maximal -Rn waves/tubespit-45-cinky1.txt
./maximal -Rn waves/tubespit-46-cinky2.txt
./maximal -Rn waves/tubespit-47-cycle6.txt
./maximal -Rn waves/tubespit-48-tbdslp.txt
./maximal -Rn waves/tubespit-49-cyctip.txt
./maximal -Rn waves/tubespit-50-cyctip.txt
./maximal -Rn waves/tubespit-51-cyctip.txt
./maximal -Rn waves/tubespit-52-cyctip.txt
./maximal -Rn waves/tubespit-53-impkhp.txt
./maximal -Rn waves/tubespit-54-impkhp.txt
./maximal -Rn waves/tubespit-55-impkhp.txt
./maximal -Rn waves/tubespit-56-tbslp2.txt
./maximal -Rn waves/tubespit-57-tbslp2.txt
./maximal -Rn waves/tubespit-58-tcycle.txt
./maximal -Rn waves/tubespit-59-tcycle.txt
./maximal -Rn waves/tubespit-60-tbslp2.txt 
./maximal -Rn waves/tubespit-61-tghost.txt 
./maximal -Rn waves/tubespit-62-tuckup.txt
./maximal -Rn waves/tubespit-63-cnudge.txt
./maximal -Rn waves/tubespit-64-sndge0.txt
./maximal -Rn waves/tubespit-64-sndge1.txt
./maximal -Rn waves/tubespit-64-sndge2.txt
./maximal -Rn waves/tubespit-64-sndge3.txt
./maximal -Rn waves/tubespit-64-sndge4.txt
./maximal -Rn waves/tubespit-64-sndge5.txt
./maximal -Rn waves/tubespit-64-sndge6.txt
./maximal -Rn waves/tubespit-64-sndge7.txt
./maximal -Rn waves/tubespit-64-sndge8.txt
./maximal -Rn waves/tubespit-64-sndge9.txt
./maximal -Rn waves/tubespit-65-consen.txt
./maximal -Rn waves/tubespit-66-consen.txt
./maximal -Rn waves/tubespit-67-bslclr.txt 
./maximal -Rn waves/tubespit-68-dRaggd.txt 
./maximal -Rn waves/tubespit-69-ktrans.txt
./maximal -Rn waves/tubespit-70-ktrans.txt
./maximal -Rn waves/tubespit-71-ktrans.txt
./maximal -Rn waves/tubespit-72-ktrans.txt
./maximal -Rn waves/tubespit-73-ktrans.txt
./maximal -Rn waves/tubespit-74-ktrans.txt
./maximal -Rn waves/tubespit-75-ktrans.txt
./maximal -Rn waves/tubespit-76-ktrans.txt
./maximal -Rn waves/tubespit-77-ktrans.txt
./maximal -Rn waves/tubespit-78-ktrans.txt
./maximal -Rn waves/tubespit-79-kcheck.txt
./maximal -Rn waves/tubespit-80-kcheck.txt
./maximal -Rn waves/tubespit-81-kcheck.txt
./maximal -Rn waves/tubespit-82-kcheck.txt
./maximal -Rn waves/tubespit-83-shadow.txt
./maximal -Rn waves/tubespit-84-shadow.txt
./maximal -Rn waves/tubespit-85-adjDTH.txt
./maximal -Rn waves/tubespit-86-adjDTH.txt
./maximal -Rn waves/tubespit-87-adjDTH.txt
./surfboard-checkmha

